import streamlit as st


def render() -> None:
    st.title("📝 Neurology")

    with st.expander("EEG", expanded=False):
        st.subheader("Normal EEG Rhythms")
        st.markdown(
            "| Rhythm | Frequency | Location | Clinical Significance |\n"
            "| --- | --- | --- | --- |\n"
            "| **Alpha (α)** | 8–13 Hz | Posterior (occipital) | Dominant rhythm in relaxed, awake adults with eyes closed. Attenuates (\"blocks\") with eye opening. Absence or asymmetry suggests posterior structural lesion. |\n"
            "| **Beta (β)** | 13–30 Hz | Frontal / diffuse | Associated with alertness, active thinking, and medication effects. Enhanced by benzodiazepines and barbiturates. Focal attenuation suggests underlying cortical lesion. |\n"
            "| **Theta (θ)** | 4–7 Hz | Variable | Normal in drowsiness and sleep. Focal theta in an awake adult suggests underlying structural or functional abnormality. Diffuse theta indicates mild encephalopathy. |\n"
            "| **Delta (δ)** | < 4 Hz | Variable | Normal in deep (N3) sleep. In awake adults: focal delta indicates structural lesion (tumor, stroke, abscess); diffuse delta indicates moderate-to-severe encephalopathy. |\n"
            "| **Mu (μ)** | 8–13 Hz | Central (C3/C4) | Arc-shaped rhythm over motor cortex. Attenuates with contralateral hand movement or even thinking about movement. No pathological significance — do not confuse with seizure activity. |\n"
            "| **Lambda (λ)** | Sharp transients | Occipital | Positive sharp waves occurring with visual scanning/saccades. Normal variant seen in awake patients actively looking at complex images. |"
        )

        st.divider()
        st.subheader("Sleep-Related Normal Patterns")
        st.markdown(
            "| Pattern | Stage | Description |\n"
            "| --- | --- | --- |\n"
            "| **Vertex sharp waves (V waves)** | N1 | High-amplitude, surface-negative sharp waves maximal at vertex (Cz). Normal arousal response. |\n"
            "| **Sleep spindles** | N2 | 11–16 Hz sinusoidal bursts (0.5–1.5 s) generated by thalamic reticular nucleus. Absence may indicate thalamic dysfunction. |\n"
            "| **K-complexes** | N2 | High-amplitude biphasic waves (sharp negative then slow positive) at vertex. Can be evoked by auditory stimuli. Followed by sleep spindles is classic. |\n"
            "| **Slow-wave activity** | N3 | High-amplitude (> 75 μV) delta waves occupying ≥ 20% of the epoch. Deepest non-REM sleep. |\n"
            "| **Sawtooth waves** | REM | 2–6 Hz notched theta waves over central regions, often preceding bursts of rapid eye movements. |\n"
            "| **POSTs** (positive occipital sharp transients of sleep) | N1–N2 | Positive triangular waves over occipital regions. Normal variant — do not mistake for epileptiform discharges. |"
        )

        st.divider()
        st.subheader("Benign / Normal Variants (\"Do Not Confuse with Epilepsy\")")
        st.markdown(
            "| Pattern | Description |\n"
            "| --- | --- |\n"
            "| **Wicket spikes** | Arc-shaped 6–11 Hz waves over temporal regions in adults, especially during drowsiness. Mimic temporal sharp waves but have no after-going slow wave. |\n"
            "| **Small sharp spikes (BETS)** (benign epileptiform transients of sleep) | Low-amplitude, brief spikes in drowsiness/light sleep. Temporal distribution. No clinical significance. |\n"
            "| **6 Hz phantom spike-and-wave** | Very low-amplitude spikes with prominent 6 Hz slow wave. \"FOLD\" variant (female, occipital, low amplitude, drowsiness) is benign. |\n"
            "| **14 and 6 Hz positive bursts** | Positive spikes at 14 or 6 Hz over posterior temporal regions during drowsiness/sleep. Normal variant in adolescents. |\n"
            "| **Rhythmic midtemporal theta of drowsiness (RMTD)** | Previously \"psychomotor variant.\" Notched 5–7 Hz theta over midtemporal regions. No epileptic significance. |\n"
            "| **Subclinical rhythmic electrographic discharges of adults (SREDA)** | Widespread rhythmic theta that can mimic a seizure pattern. Occurs in older adults; entirely benign. |\n"
            "| **Breach rhythm** | Increased amplitude and sharply contoured activity over a skull defect (craniotomy site). Reflects loss of skull filtering, not epileptogenicity. |"
        )

        st.divider()
        st.subheader("Epileptiform Patterns")
        st.markdown(
            "| Pattern | Description | Clinical Association |\n"
            "| --- | --- | --- |\n"
            "| **Spike** | Duration < 70 ms, sharp morphology | Focal epilepsy when localized to a region |\n"
            "| **Sharp wave** | Duration 70–200 ms | Similar significance to spikes; focal epilepsy |\n"
            "| **Spike-and-wave (3 Hz)** | Generalized, rhythmic, bisynchronous | Classic for childhood/juvenile absence epilepsy. Provoked by hyperventilation. |\n"
            "| **Spike-and-wave (slow, 1–2.5 Hz)** | Generalized, high amplitude | Lennox-Gastaut syndrome. Associated with cognitive regression, multiple seizure types. |\n"
            "| **Polyspike-and-wave** | Burst of multiple spikes followed by slow wave | Juvenile myoclonic epilepsy (JME). Provoked by photic stimulation and sleep deprivation. |\n"
            "| **Hypsarrhythmia** | Chaotic, high-amplitude multifocal spikes + slow waves | Infantile spasms (West syndrome). Treat with ACTH or vigabatrin. |\n"
            "| **Centrotemporal spikes** | Diphasic spikes over centrotemporal region, activated by sleep | Benign epilepsy with centrotemporal spikes (BECTS / Rolandic epilepsy). Self-limited; often no treatment needed. |\n"
            "| **Generalized paroxysmal fast activity (GPFA)** | Diffuse fast (10–25 Hz) bursts during sleep | Lennox-Gastaut syndrome. Often associated with tonic seizures. |\n"
            "| **Temporal intermittent rhythmic delta activity (TIRDA)** | Rhythmic delta over temporal region | Strongly associated with underlying temporal lobe epilepsy. |\n"
            "| **Frontal intermittent rhythmic delta activity (FIRDA)** | Rhythmic delta over frontal regions | Non-specific — encephalopathy, raised ICP, or deep midline lesions. Not epileptiform per se. |"
        )

        st.divider()
        st.subheader("Periodic & Rhythmic Patterns (ACNS Nomenclature)")
        st.markdown(
            "| Pattern | Description | Clinical Association |\n"
            "| --- | --- | --- |\n"
            "| **GPDs** (generalized periodic discharges) | Generalized, periodic, often triphasic morphology | Metabolic encephalopathy (hepatic, uremic, hyperammonemia), CJD, post-anoxic injury, status epilepticus. Triphasic morphology classically suggests metabolic cause but is not specific. |\n"
            "| **LPDs** (lateralized periodic discharges, formerly PLEDs) | Periodic sharp waves/spikes lateralized to one hemisphere | Acute destructive lesion (stroke, herpes encephalitis, tumor). High seizure risk (> 50%). HSV encephalitis classically shows temporal LPDs. |\n"
            "| **BIPDs** (bilateral independent periodic discharges, formerly BiPLEDs) | Independent periodic discharges from each hemisphere | Severe bilateral brain injury — anoxia, bilateral strokes, CNS infection. Very poor prognosis. |\n"
            "| **LRDA** (lateralized rhythmic delta activity) | Lateralized, rhythmic, non-periodic delta | On the ictal-interictal continuum. Higher seizure risk than LPDs in some studies. |\n"
            "| **GRDA** (generalized rhythmic delta activity) | Generalized, rhythmic, non-periodic delta | Non-specific encephalopathy. When frontal-predominant, may overlap with old \"FIRDA\" terminology. |\n"
            "| **Stimulus-induced rhythmic, periodic, or ictal discharges (SIRPIDs)** | Patterns triggered by stimulation (suctioning, turning, etc.) | Common in ICU cEEG monitoring. Clinical significance debated — may represent cortical irritability or seizure equivalent. |"
        )

        st.divider()
        st.subheader("Seizure (Ictal) Patterns")
        st.markdown(
            "| Pattern | Description |\n"
            "| --- | --- |\n"
            "| **Electrographic seizure** | Evolving pattern (frequency, morphology, or distribution) lasting ≥ 10 seconds. Classic evolution: rhythmic beta/alpha → theta → delta with expanding field. |\n"
            "| **Electroclinical seizure** | EEG seizure pattern with concurrent clinical signs (automatisms, clonic jerking, behavioral arrest). |\n"
            "| **Nonconvulsive status epilepticus (NCSE)** | Prolonged electrographic seizure activity without prominent motor manifestations. Suspect in patients with unexplained altered mental status, especially post-convulsive. Diagnose with continuous EEG. |\n"
            "| **Electrographic status epilepticus (ESE)** | Continuous seizure activity ≥ 10 minutes, or recurrent seizures occupying > 50% of any 1-hour epoch, without return to baseline. |"
        )

        st.divider()
        st.subheader("Specific Disease-Associated EEG Patterns")
        st.markdown(
            "| Pattern | Disease |\n"
            "| --- | --- |\n"
            "| **Generalized periodic discharges at ~1 Hz** | Creutzfeldt-Jakob disease (CJD) — especially sporadic. Sensitivity increases with disease progression. |\n"
            "| **Extreme delta brush** | Anti-NMDA receptor encephalitis. Rhythmic delta with superimposed fast (beta) activity. |\n"
            "| **Temporal LPDs + fever + CSF pleocytosis** | HSV encephalitis — start empiric acyclovir immediately. |\n"
            "| **Burst suppression** | Severe diffuse cerebral dysfunction: anoxic brain injury, deep anesthesia/coma, hypothermia. Alternating bursts of activity and periods of suppression (< 10 μV). |\n"
            "| **Electrocerebral inactivity (ECI)** | No cerebral electrical activity > 2 μV. Used as an ancillary test in brain death determination (with strict technical standards). |\n"
            "| **Frontal rhythmic delta with notched morphology** | Autoimmune / anti-LGI1 encephalitis — faciobrachial dystonic seizures. |\n"
            "| **Photoparoxysmal response** | Generalized spike/polyspike-and-wave triggered by photic stimulation. Associated with JME, progressive myoclonic epilepsies, and photosensitive epilepsies. |"
        )
