from typing import Dict, List, Tuple

MED_POINT_FIELDS: List[Tuple[str, str]] = [
    ("dose", "Dose"),
    ("onset_peak_duration", "Onset of action / peak effect / duration"),
    ("mechanism", "Mechanism"),
    ("contra", "Contraindications / cautions"),
    ("side_effects", "Side effects"),
    ("fun_fact", "Fun fact"),
]

RRT_MED_GUIDE: Dict[str, Dict[str, object]] = {
    "Bradycardia (symptomatic)": {
        "when_to_use": "For unstable/symptomatic bradycardia (hypotension, shock, altered mental status, chest pain).",
        "medications": [
            {
                "name": "Atropine",
                "dose": "1 mg IV bolus every 3-5 minutes; max cumulative dose 3 mg.",
                "onset_peak_duration": "Onset about 1 minute (IV); peak about 2-4 minutes; duration often about 30-60 minutes (can be longer in older adults).",
                "mechanism": "Antimuscarinic (vagolytic): blocks cardiac muscarinic receptors, which increases SA node firing and AV nodal conduction; minimal direct contractility effect.",
                "contra": "Contraindicated after cardiac transplant (asystole risk). Usually ineffective and may worsen Mobitz II or 3rd-degree AV block with wide QRS. Avoid doses under 0.5 mg (paradoxical bradycardia risk). Use caution in narrow-angle glaucoma, urinary or GI obstruction, marked tachycardia, severe hypertension, and heat illness.",
                "side_effects": "Tachycardia, mydriasis/blurred vision, dry mouth, urinary retention, decreased GI motility/constipation, hyperthermia, and delirium (especially in older adults).",
                "fun_fact": "The name comes from Atropa belladonna; historical accounts link belladonna eye drops to pupil dilation, including stories about Cleopatra-era beauty practices.",
            },
            {
                "name": "Epinephrine infusion",
                "dose": "2-10 mcg/min IV infusion; in peri-arrest some teams start at 10 mcg/min and then down-titrate.",
                "onset_peak_duration": "Onset under 1 minute; peak effect within minutes; duration is brief and highly titratable while running.",
                "mechanism": "Alpha and beta agonist: raises heart rate, contractility, and vascular tone to improve perfusion.",
                "contra": "No absolute contraindication in peri-arrest; use caution with active tachyarrhythmias, severe hypertension, and ongoing myocardial ischemia.",
                "side_effects": "Tachycardia, arrhythmias, hypertension, anxiety/tremor, hyperglycemia, elevated lactate, and peripheral ischemia (especially with high doses or extravasation).",
                "fun_fact": "Push-dose epinephrine boluses (for example 20-40 mcg) are often used as a bridge while an infusion is being started.",
            },
            {
                "name": "Dopamine infusion",
                "dose": "5-20 mcg/kg/min IV infusion, titrate to perfusion.",
                "onset_peak_duration": "Onset about 5 minutes; peak within minutes after rate changes; duration short after discontinuation.",
                "mechanism": "Dose-dependent catecholamine effect (beta then alpha at higher doses) increasing chronotropy, inotropy, and vasoconstriction.",
                "contra": "Avoid in uncontrolled tachyarrhythmias or pheochromocytoma; correct severe hypovolemia first when possible.",
                "side_effects": "Tachycardia, arrhythmias, nausea, headache, and extravasation injury with local tissue ischemia.",
                "fun_fact": "At higher infusion ranges, dopamine behaves mainly as a vasopressor rather than a renal-protective drug.",
            },
        ],
    },
    "Hypoxia / severe bronchospasm": {
        "when_to_use": "For RRTs with respiratory distress and hypoxemia, including severe asthma/COPD exacerbation patterns.",
        "medications": [
            {
                "name": "Albuterol (nebulized)",
                "dose": "2.5 mg nebulized every 20 minutes for 3 doses, or continuous 10-15 mg/hour.",
                "onset_peak_duration": "Onset about 5 minutes; peak about 30-60 minutes; duration about 3-6 hours.",
                "mechanism": "Beta-2 agonist causing bronchodilation and improved airflow.",
                "contra": "Use caution with severe tachyarrhythmias, significant hypokalemia, or active myocardial ischemia.",
                "side_effects": "Tremor, tachycardia, palpitations, anxiety, hypokalemia, and possible lactate rise.",
                "fun_fact": "High-dose beta-2 agonism also shifts potassium intracellularly, so albuterol can transiently help in hyperkalemia.",
            },
            {
                "name": "Ipratropium (nebulized)",
                "dose": "0.5 mg nebulized every 20 minutes for 3 doses (often paired with albuterol).",
                "onset_peak_duration": "Onset about 15 minutes; peak about 1-2 hours; duration about 4-6 hours.",
                "mechanism": "Inhaled antimuscarinic that reduces vagal bronchoconstriction.",
                "contra": "Avoid with known hypersensitivity to ipratropium or atropine derivatives; caution in glaucoma and urinary retention.",
                "side_effects": "Dry mouth, bitter taste, blurred vision if aerosol reaches eyes, urinary retention, and rare paradoxical bronchospasm.",
                "fun_fact": "Because it is a quaternary ammonium compound, it has minimal CNS penetration compared with atropine.",
            },
            {
                "name": "Methylprednisolone",
                "dose": "125 mg IV once (or equivalent systemic steroid).",
                "onset_peak_duration": "Clinical onset is delayed (about 1-2 hours); peak effect several hours later; duration generally 12-36 hours.",
                "mechanism": "Glucocorticoid that suppresses airway inflammation and reduces late-phase inflammatory worsening.",
                "contra": "No absolute contraindication in life-threatening bronchospasm; use caution with severe hyperglycemia, active infection, GI bleeding risk, or severe psychosis.",
                "side_effects": "Hyperglycemia, mood/mental-status changes, fluid retention, hypertension, and increased infection risk with repeated doses.",
                "fun_fact": "Steroids do not provide immediate bronchodilation; they are given early to reduce delayed deterioration and relapse.",
            },
            {
                "name": "Magnesium sulfate",
                "dose": "2 g IV over 15-20 minutes in severe bronchospasm.",
                "onset_peak_duration": "Onset during infusion; peak near end of infusion; effect may last hours depending on renal clearance.",
                "mechanism": "Functional calcium antagonism with smooth muscle relaxation and membrane stabilization.",
                "contra": "Use caution with myasthenia gravis, high-grade heart block, severe renal failure, or hypotension.",
                "side_effects": "Flushing, warmth, nausea, hypotension, bradycardia, and (at high levels) hyporeflexia or respiratory depression.",
                "fun_fact": "Magnesium is also a key therapy for torsades de pointes and eclampsia.",
            },
        ],
    },
    "Seizure / status epilepticus": {
        "when_to_use": "For ongoing seizure activity or recurrent seizures without return to baseline.",
        "medications": [
            {
                "name": "Lorazepam",
                "dose": "4 mg IV over 2 minutes; may repeat once after 5-10 minutes.",
                "onset_peak_duration": "Onset about 1-3 minutes IV; peak about 5-15 minutes; anticonvulsant effect often lasts about 6-12 hours.",
                "mechanism": "Benzodiazepine that enhances GABA-A activity and suppresses neuronal firing.",
                "contra": "Use caution in severe respiratory depression, hemodynamic instability, or benzodiazepine hypersensitivity.",
                "side_effects": "Sedation, respiratory depression, hypotension, and paradoxical agitation (uncommon).",
                "fun_fact": "Compared with diazepam, lorazepam has more durable CNS anticonvulsant effect after IV dosing.",
            },
            {
                "name": "Midazolam (if no IV access)",
                "dose": "10 mg IM once (or 5 mg IV/IN depending route and protocol).",
                "onset_peak_duration": "IM onset about 5-10 minutes (faster IV/IN); peak around 10-20 minutes; duration about 1-2 hours.",
                "mechanism": "Benzodiazepine that potentiates GABA-A mediated inhibitory signaling.",
                "contra": "Use caution in respiratory depression, shock, severe hypotension, or benzodiazepine hypersensitivity.",
                "side_effects": "Sedation, respiratory depression, hypotension, amnesia, and occasional paradoxical agitation.",
                "fun_fact": "Its formulation allows practical IM or intranasal use when immediate IV access is not available.",
            },
            {
                "name": "Levetiracetam",
                "dose": "60 mg/kg IV loading dose (max 4,500 mg), typically over 10-15 minutes.",
                "onset_peak_duration": "Onset during infusion; peak at end of infusion; half-life about 6-8 hours (longer with renal dysfunction).",
                "mechanism": "Binds synaptic vesicle protein SV2A, reducing excitatory neurotransmitter release.",
                "contra": "No absolute emergency contraindication; dose-adjust in renal impairment and monitor for behavioral adverse effects.",
                "side_effects": "Somnolence, dizziness, irritability, agitation, and behavioral change.",
                "fun_fact": "Levetiracetam has relatively few drug-drug interactions because it is not a significant CYP inducer/inhibitor.",
            },
            {
                "name": "Fosphenytoin",
                "dose": "20 mg PE/kg IV loading dose (max infusion rate 150 mg PE/min).",
                "onset_peak_duration": "Onset about 10-20 minutes after loading; peak antiseizure effect shortly after conversion to phenytoin.",
                "mechanism": "Prodrug of phenytoin that blocks voltage-gated sodium channels and limits repetitive neuronal firing.",
                "contra": "Avoid in sinus bradycardia, SA block, 2nd/3rd-degree AV block, or Adams-Stokes syndrome.",
                "side_effects": "Hypotension, arrhythmias (especially with rapid infusion), pruritus, nystagmus, and ataxia.",
                "fun_fact": "Fosphenytoin is less irritating to veins than phenytoin and can be given IM if needed.",
            },
        ],
    },
    "Hypotension / shock": {
        "when_to_use": "For undifferentiated shock after immediate airway/oxygen support and rapid bedside evaluation.",
        "medications": [
            {
                "name": "Isotonic crystalloid",
                "dose": "500-1,000 mL IV bolus, then reassess fluid responsiveness.",
                "onset_peak_duration": "Immediate effect during infusion; peak intravascular effect during/just after bolus; duration variable and often short in distributive states.",
                "mechanism": "Expands intravascular volume to increase preload and stroke volume in fluid-responsive patients.",
                "contra": "Use caution in pulmonary edema, severe heart failure, ESRD, or known volume overload.",
                "side_effects": "Fluid overload, edema, dilutional coagulopathy (large volumes), and hyperchloremic acidosis with large-volume normal saline.",
                "fun_fact": "Balanced crystalloids may reduce chloride load compared with normal saline in large-volume resuscitation.",
            },
            {
                "name": "Norepinephrine infusion",
                "dose": "0.05-1 mcg/kg/min IV infusion, titrate to MAP/perfusion goals.",
                "onset_peak_duration": "Onset under 1 minute; peak within 1-2 minutes after rate changes; duration short when stopped.",
                "mechanism": "Primarily alpha-1 vasoconstriction with some beta-1 support, increasing vascular tone and perfusion pressure.",
                "contra": "Relative contraindication in profound uncorrected hypovolemia; caution for digital/mesenteric ischemia and extravasation injury.",
                "side_effects": "Peripheral ischemia, hypertension, arrhythmias, and local tissue necrosis if extravasated.",
                "fun_fact": "Norepinephrine is the usual first-line vasopressor for septic and vasodilatory shock.",
            },
            {
                "name": "Vasopressin",
                "dose": "0.03 units/min IV infusion (fixed dose) as adjunct in refractory vasodilatory shock.",
                "onset_peak_duration": "Onset in minutes; peak effect often within about 15 minutes; short plasma half-life with continuous-infusion use.",
                "mechanism": "V1 receptor agonism causes non-adrenergic vasoconstriction, often used as catecholamine-sparing support.",
                "contra": "Use caution in coronary/peripheral ischemia, mesenteric ischemia risk, and hyponatremia-prone patients.",
                "side_effects": "Ischemia, hyponatremia/water retention, abdominal cramping, and reduced cardiac output in some patients.",
                "fun_fact": "Vasopressin can still work when severe acidemia blunts catecholamine responsiveness.",
            },
            {
                "name": "Epinephrine infusion",
                "dose": "0.02-0.5 mcg/kg/min IV infusion when additional inotropy/vasopressor support is needed.",
                "onset_peak_duration": "Onset under 1 minute; peak within minutes; duration rapidly titratable.",
                "mechanism": "Mixed alpha/beta agonist providing inotropy, chronotropy, and vasoconstriction.",
                "contra": "No absolute contraindication in life-threatening shock; use caution with tachyarrhythmias and active myocardial ischemia.",
                "side_effects": "Tachycardia, arrhythmias, hypertension, hyperglycemia, and lactate rise.",
                "fun_fact": "Epinephrine often increases lactate through beta-2 effects, which does not always indicate worsening tissue hypoxia.",
            },
        ],
    },
    "Anaphylaxis": {
        "when_to_use": "For suspected anaphylaxis with airway compromise, hypotension, bronchospasm, or multi-system allergic reaction.",
        "medications": [
            {
                "name": "Epinephrine IM (1 mg/mL)",
                "dose": "0.3-0.5 mg IM into lateral thigh; repeat every 5-15 minutes as needed.",
                "onset_peak_duration": "Onset usually within 3-5 minutes IM; peak around 5-10 minutes; duration often 10-20 minutes.",
                "mechanism": "Alpha-1 vasoconstriction plus beta bronchodilation/inotropy; also reduces mediator release from mast cells.",
                "contra": "No absolute contraindication in true anaphylaxis.",
                "side_effects": "Palpitations, tremor, anxiety, headache, and transient hypertension; serious arrhythmia/ischemia is uncommon at IM dosing.",
                "fun_fact": "Anterolateral thigh IM injection provides more reliable absorption than subcutaneous injection.",
            },
            {
                "name": "Diphenhydramine",
                "dose": "25-50 mg IV/IM adjunctive therapy.",
                "onset_peak_duration": "IV onset about 2-5 minutes (IM slower); peak around 1-2 hours; duration about 4-6 hours.",
                "mechanism": "H1 receptor blockade to reduce itching, hives, and other histamine-mediated symptoms.",
                "contra": "Use caution in older adults, glaucoma, urinary retention, delirium risk, and concomitant sedatives.",
                "side_effects": "Sedation, anticholinergic effects, confusion, and hypotension (especially with rapid IV administration).",
                "fun_fact": "Diphenhydramine is adjunctive only; it does not replace epinephrine for airway edema or shock.",
            },
            {
                "name": "Famotidine",
                "dose": "20 mg IV adjunctive therapy.",
                "onset_peak_duration": "Onset within about 15-30 minutes; peak around 1-3 hours; duration roughly 10-12 hours.",
                "mechanism": "H2 receptor blockade that can complement H1 blockade for histamine-mediated symptoms.",
                "contra": "Dose-adjust in renal dysfunction; use caution with prolonged QT risk in severe renal impairment.",
                "side_effects": "Headache, dizziness, diarrhea or constipation, and rare bradyarrhythmia/QT effects.",
                "fun_fact": "Adding H2 blockade may improve cutaneous symptoms, but epinephrine remains the life-saving primary therapy.",
            },
            {
                "name": "Methylprednisolone",
                "dose": "125 mg IV adjunctive therapy (does not replace epinephrine).",
                "onset_peak_duration": "Delayed onset (about 1-2 hours); peak several hours later; duration generally 12-36 hours.",
                "mechanism": "Glucocorticoid effect on inflammatory gene expression to blunt late-phase inflammation.",
                "contra": "No immediate absolute contraindication in severe anaphylaxis; use caution with hyperglycemia, infection risk, active GI bleeding, and severe psychosis.",
                "side_effects": "Hyperglycemia, mood changes/delirium, fluid retention, hypertension, and immunosuppression with repeated exposure.",
                "fun_fact": "Evidence for preventing biphasic anaphylaxis is mixed, so steroids are supportive rather than definitive therapy.",
            },
        ],
    },
}
