from typing import Dict, List, Tuple

MED_POINT_FIELDS: List[Tuple[str, str]] = [
    ("dose", "Dose"),
    ("onset_peak_duration", "Pharmacokinetics"),
    ("mechanism", "Mechanism"),
    ("contra", "Contraindications / cautions"),
    ("side_effects", "Side effects"),
    ("fun_fact", "Fun fact"),
]

RRT_MED_GUIDE: Dict[str, Dict[str, object]] = {
    "Bradycardia": {
        "medications": [
            {
                "name": "Atropine",
                "item_type": "medication",
                "dose": "1 mg IV bolus every 3-5 minutes; max cumulative dose 3 mg.",
                "onset_peak_duration": "Onset 1 minute; peak 2-4 minutes; duration 30-60 minutes.",
                "mechanism": "Antimuscarinic (vagolytic): blocks cardiac muscarinic receptors, which increases SA node firing and AV nodal conduction; minimal direct contractility effect.",
                "contra": "May worsen Mobitz II or CHB with wide QRS. Contraindicated after cardiac transplant (asystole). Use caution in acute coronary syndrome.",
                "fun_fact": "The name comes from Atropa belladonna (Nightshade); Belladonna named because Cleopatra used the eye drops for pupil dilation as a beauty product.",
            },
            {
                "name": "Temporary pacing (transcutaneous/transvenous)",
                "item_type": "procedure",
                "summary": "Start transcutaneous pacing immediately while preparing medications.",
                "steps": [
                    "Set a backup rate (commonly 60-80/min), then increase mA until electrical capture is seen.",
                    "Confirm mechanical capture with pulse/BP or bedside ultrasound, not ECG alone.",
                    "If transcutaneous capture is unreliable or prolonged support is needed, escalate to transvenous pacing.",
                ],
                "cautions": "Pain and muscle contraction are common; provide analgesia/sedation when blood pressure allows. Re-check capture frequently.",
            },
            {
                "name": "Epinephrine infusion",
                "item_type": "medication",
                "dose": "2-10 mcg/min IV infusion; in peri-arrest some teams start at 10 mcg/min and then down-titrate.",
                "onset_peak_duration": "Onset under 1 minute; peak effect within minutes; duration is brief and highly titratable while running.",
                "mechanism": "Alpha and beta agonist: acts on the whole heart, unlike atropine, making it more likely to be successful.",
                "contra": "None.",
                "comments": "If epinephrine not available, put a vial of cardiac epinephrine in 1L NS, mix the bag, and run it at 120 mL/hr - 600 ml/hr to approximate 2-10 mcg/min.",
            },
            {
                "name": "Calcium",
                "item_type": "medication",
                "dose": "1g CaCl (CVC) or 3g CaGluc (PIV). If HyperK can consider redosing. iSTAT might be helpful.",
                "comments": "Calcium-responsive bradycardias: HyperK, HypoCa, HyperMg, CCB, BB",
            },
        ],
    },
    "Cardiac": {
        "medications": [
            {
                "name": "Vagal maneuvers (stable regular narrow-complex SVT)",
                "item_type": "procedure",
                "summary": "Best first maneuver is the modified Valsalva. Use only in a hemodynamically stable patient with likely regular narrow-complex re-entrant SVT.",
                "steps": [
                    "Modified Valsalva (best first): start semi-recumbent at about 45 degrees. Have the patient generate about 40 mm Hg of pressure for 15 seconds (for example by forcefully blowing into a syringe or manometer). Immediately lay the patient flat and passively raise the legs to about 45 degrees for 15 seconds, then return to the semi-recumbent position and reassess rhythm after about 45 seconds.",
                    "The modified technique is meaningfully more effective than the standard seated/semi-recumbent Valsalva and is a good first attempt while IV access, pads, and adenosine are being prepared.",
                    "Standard Valsalva: if the modified version is not feasible, use a firm 15-second strain against a closed glottis or pressure target, but expect lower conversion rates.",
                    "Carotid sinus massage is a backup option only: one side at a time with continuous ECG monitoring, gentle pressure over the carotid sinus for about 5-10 seconds, then reassess before considering the other side. Never massage both sides simultaneously.",
                    "Cold facial stimulus / diving reflex is mainly a pediatric or occasional fallback maneuver; in adults it is generally less useful than modified Valsalva.",
                ],
                "cautions": "Do not use vagal maneuvers as a delay tactic in unstable tachycardia. Avoid carotid massage with carotid bruit, known significant carotid disease, or recent TIA/stroke; many protocols also avoid it after recent MI, VF, or VT.",
            },
            {
                "name": "Synchronized cardioversion (DCCV)",
                "item_type": "procedure",
                "summary": "Use for tachycardia with serious signs/symptoms caused by the rhythm. Sedate whenever feasible, but do not delay if the patient is crashing.",
                "steps": [
                    "Place pads, attach monitor/defibrillator, establish IV access, and have suction/airway equipment ready.",
                    "Turn SYNC on and confirm the device is marking each QRS/R wave before delivering the shock.",
                    "Use current AHA starting energies: atrial fibrillation 200 J, atrial flutter 200 J, regular narrow-complex tachycardia 100 J, monomorphic VT with a pulse 100 J.",
                    "If the first attempt fails, escalate energy per device/patient response and remember many defibrillators require you to re-enable synchronization after each shock.",
                    "If synchronization is not possible and the patient is critically unstable, move to unsynchronized shock.",
                ],
                "cautions": "Do not use synchronized cardioversion for polymorphic VT, VF, or pulseless VT. Shock delivery may be delayed if the monitor cannot synchronize reliably.",
            },
            {
                "name": "Defibrillation (unsynchronized shock)",
                "item_type": "procedure",
                "summary": "Use for VF, pulseless VT, and polymorphic VT; in a crashing unstable tachyarrhythmia, use if synchronization cannot be achieved fast enough.",
                "steps": [
                    "Turn SYNC off before shocking. Charge while CPR continues when appropriate, then clear and shock with minimal interruption.",
                    "Adult biphasic defibrillation: use the manufacturer recommendation (commonly 120-200 J initial); if unknown, use the maximum available setting.",
                    "Adult monophasic defibrillation: 360 J.",
                    "After the shock, resume CPR immediately for 2 minutes before the next rhythm check if the patient is pulseless.",
                    "Second and later biphasic shocks should be equivalent or higher energy per device guidance.",
                ],
                "cautions": "Do not pause to check a pulse or rhythm for long after a shock in cardiac arrest; prioritize immediate chest compressions.",
            },
            {
                "name": "Transcutaneous pacing",
                "item_type": "procedure",
                "summary": "Use for symptomatic bradycardia when atropine is ineffective or unlikely to work; prepare for transvenous pacing if capture is unreliable or prolonged support is expected.",
                "steps": [
                    "Place pacing/defibrillation pads, attach monitor, and provide analgesia/sedation if blood pressure allows because pacing is painful.",
                    "Set a pacing rate, commonly 60-80/min.",
                    "Increase current (mA) until electrical capture appears on the monitor, then confirm mechanical capture with a pulse, blood pressure, or bedside ultrasound - not ECG alone.",
                    "Set the output slightly above the capture threshold and reassess capture frequently because it can be lost with movement or pad issues.",
                    "While pacing, continue to correct reversible causes and prepare dopamine/epinephrine infusion or transvenous pacing when indicated.",
                ],
                "cautions": "Electrical spikes alone do not prove effective perfusion. If the patient remains unstable despite apparent capture, reassess immediately.",
            },
        ],
    },
    "Active Ongoing Seizure": {
        "medications": [
            {
                "name": "Lorazepam",
                "item_type": "medication",
                "dose": "4 mg IV over 2 minutes; may repeat once in 5-10 minutes. 0.1 mg/kg, maximum rate 2 mg/min is also okay.",
                "onset_peak_duration": "Onset 1-3 minutes IV; peak 5-15 minutes; anticonvulsant effect usually several hours.",
            },
            {
                "name": "Midazolam (if no IV)",
                "item_type": "medication",
                "dose": "10 mg IM once (or 10 mg IN/IV).",
                "onset_peak_duration": "IM onset about 5-10 minutes (faster IV/IN).",
            },
            {
                "name": "Levetiracetam",
                "item_type": "medication",
                "dose": "If seizures still present, give 60 mg/kg, max 4500 mg, infuse over 10 minutes.",
                "comments": "Give it whenever it arrives but move on to next steps.",
            },
            {
                "name": "D50",
                "item_type": "medication",
                "comments": "Don't forget to check glucose",
            },
            {
                "name": "Hypertonic sodium bicarbonate",
                "item_type": "medication",
                "dose": "2 ampules (100 mEq) of 1 mEq/ml concentration",
                "comments": "Hyponatremia is an uncommon cause of seizures but needs immediate treatment if present",
            },
            {
                "name": "Thiamine",
                "item_type": "medication",
                "comments": "Known cause of seizures. When in doubt. OK to give.",
            },
            {
                "name": "Ketamine",
                "item_type": "medication",
                "dose": "1 mg/kg slow IV push over 2 minutes",
                "comments": "When you are thinking about ketamine you are in intubation territory. Call for propofol gtt or midazolam bolus + gtt, paralytic, and norepinephrine",
            },
        ],
    },
    "Neuro Exams": {
        "medications": [
            {
                "name": "HINTS exam (acute vestibular syndrome only)",
                "item_type": "procedure",
                "summary": "Use only in a currently symptomatic patient with continuous acute vestibular syndrome (ongoing vertigo/dizziness, spontaneous nystagmus, nausea/vomiting, gait unsteadiness).",
                "steps": [
                    "Do not use HINTS for episodic dizziness, clearly triggered positional dizziness, or a patient who is no longer symptomatic at the time of exam.",
                    "Head impulse: ask patient to fix on your nose and deliver small rapid head turns. An abnormal corrective saccade suggests peripheral vestibulopathy; a normal head impulse in acute vestibular syndrome is a central red flag.",
                    "Nystagmus: look in primary gaze and with lateral gaze. Unidirectional horizontal nystagmus favors peripheral disease; direction-changing, vertical, or torsional nystagmus favors central pathology.",
                    "Test of skew: alternate cover each eye while patient fixes on a target. Vertical realignment after uncovering is concerning for a central lesion.",
                    "HINTS is concerning for stroke if any one central sign is present. New unilateral hearing loss (HINTS+) also raises concern for central ischemia, especially AICA territory.",
                ],
                "cautions": "A dangerous HINTS can outperform early MRI in expert hands, but misuse is common. If concern for posterior circulation stroke remains high, treat it as stroke regardless of a reassuring bedside exam.",
            },
            {
                "name": "Dix-Hallpike maneuver (posterior canal BPPV)",
                "item_type": "procedure",
                "summary": "Use for brief, triggered positional vertigo when posterior canal BPPV is suspected; do not use it as a substitute for HINTS in continuous acute vestibular syndrome.",
                "steps": [
                    "Start seated. Turn the head 45 degrees toward the side being tested, then bring the patient quickly to supine with the head hanging about 20 degrees below horizontal and the tested ear down.",
                    "Watch the eyes and ask about vertigo for at least 30 seconds after positioning.",
                    "A positive test for posterior canal BPPV is reproduction of vertigo with classic torsional, upbeating nystagmus when the affected ear is down.",
                    "Repeat on the opposite side if the first side is negative.",
                    "If the maneuver causes horizontal nystagmus or symptoms are strongly suggestive but Dix-Hallpike is negative, consider lateral canal BPPV and perform a supine roll test.",
                ],
                "cautions": "Use caution or a modified maneuver in patients with significant cervical spine disease, severe back pain, vascular instability, or limited neck extension.",
            },
            {
                "name": "Meningitis bedside exam",
                "item_type": "procedure",
                "summary": "Look for meningeal irritation and encephalopathy, but do not rely on bedside signs alone to rule meningitis in or out.",
                "steps": [
                    "Screen for the syndrome first: fever, headache, neck pain/stiffness, photophobia, vomiting, altered mental status, seizure, petechial/purpuric rash, and immunocompromise.",
                    "Assess nuchal rigidity with gentle passive neck flexion; resistance or pain supports meningeal irritation.",
                    "Brudzinski sign: passive neck flexion causing involuntary hip/knee flexion suggests meningeal irritation.",
                    "Kernig sign: with hip and knee flexed to 90 degrees, pain/resistance on knee extension suggests meningeal irritation.",
                    "Perform a focused neuro exam for focal deficits, cranial neuropathies, papilledema, or markedly depressed mental status, which raise concern for encephalitis, mass effect, or elevated ICP.",
                ],
                "cautions": "Classic meningeal signs have limited sensitivity. Their absence does not exclude bacterial meningitis, especially in older, immunocompromised, or altered patients.",
            },
            {
                "name": "Intubated neuro exam",
                "item_type": "procedure",
                "summary": "Use a structured exam and document confounders; the FOUR score is often more useful than GCS when the patient is intubated.",
                "steps": [
                    "Before interpreting the exam, document sedatives, analgesics, paralytics, hypothermia, severe metabolic derangements, and whether a sedation pause is safe.",
                    "Check pupils first: size, symmetry, and reactivity. Then assess gaze position, spontaneous eye opening, tracking, and any gaze deviation.",
                    "Assess motor response to voice and to central/peripheral painful stimulus: localizing, withdrawing, extensor/flexor posturing, flaccidity, and any asymmetry.",
                    "Check brainstem reflexes when relevant: corneal reflexes, cough with suctioning, and gag if it will change management.",
                    "Assess respiratory drive and vent interaction: breathing above the set rate, triggering the ventilator, or absent spontaneous effort.",
                    "Trend the same structured exam over time and document the best response, laterality, and any change from prior exam.",
                ],
                "cautions": "Do not overcall absent responses while paralytics or deep sedation are active. New asymmetry, loss of brainstem reflexes, or worsening exam should prompt urgent escalation.",
            },
        ],
    },
    "Rheumatologic Exam": {
        "medications": [
            {
                "name": "Rheumatoid arthritis - classic findings",
                "item_type": "procedure",
                "summary": "Think inflammatory symmetric small-joint disease.",
                "steps": [
                    "Inspect and palpate MCP, PIP, and wrists for symmetric boggy synovitis, warmth, tenderness, and reduced ROM.",
                    "Typical chronic deformities: ulnar deviation at MCPs, swan-neck deformities, boutonniere deformities, and volar subluxation.",
                    "Look for rheumatoid nodules over extensor surfaces/olecranon.",
                    "History/exam clues that fit: prolonged morning stiffness and hand squeeze pain.",
                ],
                "cautions": "Early RA may present before fixed deformities develop; absence of deformity does not exclude active inflammatory arthritis.",
            },
            {
                "name": "Systemic lupus erythematosus - classic findings",
                "item_type": "procedure",
                "summary": "Look for mucocutaneous findings plus nonerosive inflammatory arthritis.",
                "steps": [
                    "Inspect for malar rash over cheeks/nasal bridge that classically spares the nasolabial folds.",
                    "Look for oral or nasal ulcers, non-scarring alopecia, and photosensitive rash.",
                    "Examine hands for tender/swollen joints, usually nonerosive and often involving small joints.",
                    "Check for serositis clues on exam/history: pleuritic chest pain or pericarditic features.",
                ],
                "cautions": "SLE is multisystem; skin findings may be absent at presentation.",
            },
            {
                "name": "Dermatomyositis - classic findings",
                "item_type": "procedure",
                "summary": "Pair proximal weakness with characteristic skin disease.",
                "steps": [
                    "Test proximal strength: difficulty rising from a chair, climbing stairs, or combing hair suggests proximal muscle weakness.",
                    "Inspect eyelids for heliotrope rash and hands for Gottron papules/sign over MCP/PIP/extensor surfaces.",
                    "Look for shawl sign or V-sign photodistributed erythema.",
                    "Check for mechanic's hands if antisynthetase-spectrum disease is on the differential.",
                ],
                "cautions": "Normal distal strength does not rule out inflammatory myopathy; focus on proximal groups and skin clues.",
            },
            {
                "name": "Systemic sclerosis - classic findings",
                "item_type": "procedure",
                "summary": "Skin thickening, vascular findings, and fingertip injury are the big bedside clues.",
                "steps": [
                    "Look for puffy fingers early and sclerodactyly later; assess whether skin thickening extends proximal to the MCPs.",
                    "Inspect fingertips for digital pitting, ulcers, or loss of pulp.",
                    "Look for telangiectasias and ask about/observe Raynaud phenomenon.",
                    "Check nailfold capillaries if available and note microstomia or mask-like facies in advanced disease.",
                ],
                "cautions": "Diffuse skin thickening proximal to the MCPs is especially concerning for systemic sclerosis.",
            },
            {
                "name": "Psoriatic arthritis - classic findings",
                "item_type": "procedure",
                "summary": "Think psoriasis, nails, dactylitis, DIP disease, and enthesitis.",
                "steps": [
                    "Inspect skin and scalp for psoriasis; do not forget hidden areas such as gluteal cleft, umbilicus, and behind ears.",
                    "Look at nails for pitting, onycholysis, and dystrophy.",
                    "Examine for dactylitis ('sausage digit') and tenderness at entheses such as Achilles or plantar fascia insertion.",
                    "Check for DIP-predominant arthritis or asymmetric oligoarthritis.",
                ],
                "cautions": "Psoriasis may be subtle or historical; nail disease and dactylitis are especially useful bedside clues.",
            },
            {
                "name": "Gout - classic findings",
                "item_type": "procedure",
                "summary": "Sudden, exquisitely painful monoarthritis is the bedside pattern.",
                "steps": [
                    "Look for podagra: abrupt onset red, hot, swollen, exquisitely tender first MTP arthritis.",
                    "Assess whether the pain peaked rapidly (often within 24 hours) and whether even light touch is intolerable.",
                    "Inspect for tophi at ears, olecranon bursae, fingers, toes, prepatellar area, or Achilles region.",
                    "Remember gout can also involve ankle, midfoot, knee, wrist, or olecranon bursa.",
                ],
                "cautions": "Classic exam supports gout, but septic arthritis still has to be excluded in an acutely inflamed joint.",
            },
            {
                "name": "Giant cell arteritis / polymyalgia rheumatica - classic findings",
                "item_type": "procedure",
                "summary": "In older adults, combine cranial ischemic symptoms with vascular exam and shoulder/hip girdle stiffness.",
                "steps": [
                    "Palpate temporal arteries for tenderness, nodularity, thickening, or reduced pulsation.",
                    "Ask specifically about new temporal headache, scalp tenderness, jaw claudication, and transient or permanent visual symptoms.",
                    "For PMR features, assess painful restricted active shoulder motion and marked morning stiffness in shoulders/neck/hips.",
                    "If vision symptoms or strong GCA features are present, escalate immediately rather than waiting for confirmatory testing.",
                ],
                "cautions": "A normal temporal artery exam does not exclude GCA.",
            },
        ],
    },
    "Skin Exam": {
        "medications": [
            {
                "name": "General skin exam approach",
                "item_type": "procedure",
                "summary": "Describe lesions before naming them.",
                "steps": [
                    "Expose the involved area fully and, when relevant, examine the entire skin surface including scalp, nails, mucosa, palms, soles, and intertriginous areas.",
                    "Describe morphology first: macule/patch, papule/plaque, vesicle/bulla, pustule, nodule, wheal, crust, scale, erosion, or ulcer.",
                    "Then describe distribution and arrangement: localized vs generalized, symmetric vs asymmetric, flexural vs extensor, dermatomal, acral, photo-distributed, annular, linear, grouped, or targetoid.",
                    "Palpate for warmth, tenderness, induration, fluctuance, skin fragility, blanching, and whether scale or crust lifts easily.",
                ],
                "cautions": "A complete skin exam can reveal important incidental findings, including hidden infection and skin cancer.",
            },
            {
                "name": "Psoriasis - classic findings",
                "item_type": "procedure",
                "summary": "Well-demarcated plaques with scale on extensor surfaces.",
                "steps": [
                    "Look for sharply demarcated erythematous plaques with thick silvery scale on elbows, knees, scalp, lower back, or gluteal cleft.",
                    "Check nails for pitting, onycholysis, subungual hyperkeratosis, or oil-drop discoloration.",
                    "Auspitz sign and Koebner phenomenon are classic clues, though not required for diagnosis.",
                ],
                "cautions": "Psoriasis can involve scalp, nails, genitals, and intertriginous areas with less obvious scale.",
            },
            {
                "name": "Atopic dermatitis - classic findings",
                "item_type": "procedure",
                "summary": "The 'itch that rashes': dry, itchy, eczematous skin.",
                "steps": [
                    "Look for xerosis, excoriations, erythematous or hyperpigmented patches/plaques, and chronic lichenification.",
                    "In older children and adults, flexural involvement is classic: antecubital fossae, popliteal fossae, neck, wrists, and hands.",
                    "Ask about personal or family history of atopy and whether itch preceded the visible rash.",
                ],
                "cautions": "Secondary infection is common; crusting, oozing, or punched-out erosions should lower your threshold to consider superinfection.",
            },
            {
                "name": "Scabies - classic findings",
                "item_type": "procedure",
                "summary": "Intensely pruritic eruption with characteristic distribution and burrows.",
                "steps": [
                    "Look for small papules, vesicles, excoriations, and short thin burrows in finger webs, wrists, elbows, axillae, belt line, groin, buttocks, penis, and around the nipples.",
                    "Nighttime itch and symptomatic close contacts are classic historical clues.",
                    "In infants or immunocompromised patients, the eruption can be more widespread and involve scalp, palms, or soles.",
                ],
                "cautions": "Adults usually do not have lesions above the neck; crusted scabies can look very different and carry a high mite burden.",
            },
            {
                "name": "Herpes zoster - classic findings",
                "item_type": "procedure",
                "summary": "Painful unilateral dermatomal vesicles.",
                "steps": [
                    "Ask about pain, burning, tingling, or allodynia preceding the rash.",
                    "Look for grouped vesicles on an erythematous base in one or two adjacent dermatomes.",
                    "The rash classically does not cross the midline; thoracic and trigeminal distributions are common.",
                ],
                "cautions": "Atypical or disseminated presentations are more likely in immunocompromised patients.",
            },
            {
                "name": "Targetoid and sloughing eruptions - classic findings",
                "item_type": "procedure",
                "summary": "Recognize true target lesions and dangerous mucosal disease.",
                "steps": [
                    "Erythema multiforme classically shows symmetric target lesions with three zones, often on extensor extremities, palms, or soles.",
                    "Stevens-Johnson syndrome / TEN should be suspected with painful dusky or purpuric macules, mucosal involvement, bullae, epidermal detachment, or positive Nikolsky-type skin fragility.",
                    "Recent high-risk medication exposure and systemic symptoms increase concern for severe cutaneous adverse reaction.",
                ],
                "cautions": "Painful skin, mucosal erosions, and skin sloughing are red flags and need urgent escalation.",
            },
            {
                "name": "Skin cancer warning lesions - classic findings",
                "item_type": "procedure",
                "summary": "Use the ABCDEs for melanoma and recognize common nonmelanoma patterns.",
                "steps": [
                    "Melanoma warning features: asymmetry, irregular border, color variegation, diameter often greater than 6 mm, and evolving change.",
                    "Basal cell carcinoma often looks pearly, shiny, translucent, telangiectatic, ulcerated, or like a sore that heals and returns.",
                    "Squamous cell carcinoma often appears as a firm hyperkeratotic papule/plaque/nodule, sometimes crusted or ulcerated.",
                ],
                "cautions": "Any lesion that is changing, bleeding, or not healing deserves attention even if it does not fit a textbook pattern.",
            },
        ],
    },
    "Anaphylaxis": {
        "medications": [
            {
                "name": "Immediate actions",
                "item_type": "procedure",
                "steps": [
                    "Ask patient to speak their name to assess for stridor. If stridor, prepare to establish an airway.",
                    "All steps happen simultaneously, including the below actions, epinephrine, and airway management.",
                    "Stop any infusions. Establish IV/IO access.",
                    "Give HFNC or NRB, place on monitor, and establish IV/IO access.",
                    "Lay patient supine with legs elevated (or left lateral if vomiting/pregnant); avoid sudden upright posture (empty ventricle syndrome)",
                    "Give epinephrine at the earliest opportunity. (Better outcomes)",
                    "Give 1-2L rapid fluids ASAP.",
                    "Rapid airway assessment and get the most experienced intubator around, prepare for emergency cricothyrotomy and have an extraglottic backup.",
                    "Check serum tryptase in addition to normal labs",
                ],
                "cautions": "Skin findings can be absent in severe reactions; treat airway/breathing/circulation compromise as anaphylaxis.",
            },
            {
                "name": "Emergency cricothyrotomy (CICO rescue airway)",
                "item_type": "procedure",
                "summary": "If cannot intubate/cannot oxygenate with worsening hypoxemia, move early to front-of-neck access.",
                "steps": [
                    "Landmarks (laryngeal handshake): palpate hyoid, thyroid cartilage, then cricothyroid membrane (CTM) between thyroid and cricoid; stabilize the larynx with non-dominant hand.",
                    "Equipment: #10 (or similarly wide) scalpel, bougie (coudé tip), suction, and a lubricated cuffed tube (often size 6.0).",
                    "If CTM palpable: make a transverse stab through skin + CTM, rotate blade 90 degrees with sharp edge caudad, and use the blade as a hook to keep the opening patent.",
                    "If CTM impalpable: make a large vertical midline skin incision, use blunt finger dissection to identify/stabilize laryngeal structures, then perform the transverse CTM stab.",
                    "Advance bougie gently into trachea along the blade/finger track; it should pass without fixed resistance. If resistance is met, do not force - withdraw slightly and redirect.",
                    "Railroad a lubricated cuffed tracheostomy tube (or a 6.0 cuffed ETT per local kit) over the bougie into the trachea, then remove bougie.",
                    "Inflate cuff, ventilate, confirm with continuous waveform capnography + chest rise, and secure tube.",
                ],
                "cautions": "Last-resort airway procedure. Keep oxygen delivery attempts ongoing during setup and follow local difficult-airway protocol.",
            },
            {
                "name": "Epinephrine (IM) - first line",
                "item_type": "medication",
                "dose": "0.5 mg IM (0.5 mL of 1 mg/mL [1:1000]) into anterolateral thigh; repeat every 5 minutes as needed.",
                "mechanism": "Alpha-1 vasoconstriction reduces edema/hypotension, beta-1 supports cardiac output, and beta-2 bronchodilates/reduces mediator release.",
            },
            {
                "name": "Epinephrine infusion (refractory symptoms)",
                "item_type": "medication",
                "dose": "If persistent respiratory/circulatory compromise after 2 IM doses + fluids, start IV epinephrine infusion (e.g., 0.05-0.1 mcg/kg/min and titrate).",
            },
            {
                "name": "Nebulized albuterol (salbutamol)",
                "item_type": "medication",
                "dose": "5 mg nebulized for persistent bronchospasm/wheezing after epinephrine.",
                "comments": "Adjunct only; never replace epinephrine with bronchodilator alone.",
            },
            {
                "name": "Glucagon (beta-blocker use, refractory hypotension/bradycardia)",
                "item_type": "medication",
                "dose": "1 to 5 mg IV over 5 minutes, then infusion 5-15 mcg/min if needed.",
                "mechanism": "Improves inotropy/chronotropy via non-beta receptor pathway.",
            },
            {
                "name": "Antihistamines and corticosteroids (adjuncts only)",
                "item_type": "medication",
                "dose": "Consider only after stabilization, mainly for persistent skin symptoms or refractory/protracted reaction per protocol.",
                "mechanism": "May improve cutaneous symptoms; delayed onset.",
            },
            {
                "name": "Observation and disposition",
                "item_type": "procedure",
                "steps": [
                    "Observe for biphasic recurrence based on severity/risk factors and local protocol.",
                    "AEdit allergy list",
                ],
            },
        ],
    },
    "Code Stroke": {
    "medications": [
        {
            "name": "Immediate steps",
            "item_type": "procedure",
            "steps": [
                "Check fingerstick glucose (treat hypoglycemia first before continuing).",
                "Determine Last Known Well (clock time), onset pattern (sudden vs stuttering), wake-up/unknown onset, and any seizure at onset.",
                "Determine baseline functional status and pre-stroke mRS (modified Rankin Scale)",
                "Focused neuro exam + NIHSS + disabling deficits.",
                "Establish IV access. Obtain weight for thrombolytic dosing.",
                "Draw labs (do not delay imaging): CBC, CMP, PT/INR, aPTT; troponin; pregnancy test if applicable.",
                "Baseline ECG and troponin are recommended but should NOT delay IV thrombolysis if otherwise eligible.",
                "Review meds (anticoagulants/antiplatelets), bleeding history, recent stroke/head trauma/surgery, and BP control feasibility.",
            ],
        },
        {
            "name": "LVO patterns (clinical clues)",
            "item_type": "procedure",
            "steps": [
                "Anterior circulation clues: forced gaze deviation, aphasia, neglect, homonymous field cut, dense unilateral weakness.",
                "Posterior circulation clues: depressed consciousness, diplopia, dysarthria, ataxia, 'crossed' deficits; consider basilar occlusion even with modest NIHSS.",
                "If high suspicion for LVO → CTA head/neck early; do not rely on NIHSS alone.",
            ],
        },

        {
            "name": "NIHSS (0–42)",
            "item_type": "procedure",
            "summary": "Perform early (baseline). Recheck with clinical changes.",
            "steps": [
                "1a LOC (0–3): 0 alert; 1 arousable to minor stimulation; 2 needs repeated/strong stimulation; 3 unresponsive/flaccid.",
                "1b Month + Age (0–2): 0 both correct; 1 one correct; 2 neither.",
                "1c 'Blink eyes' + 'Squeeze hands' (0–2): 0 both; 1 one; 2 neither.",
                "2 Horizontal gaze (0–2): 0 normal; 1 partial gaze palsy; 2 forced deviation/complete palsy not overcome by oculocephalic maneuver.",
                "3 Visual fields (0–3): 0 none; 1 partial hemianopia; 2 complete hemianopia; 3 bilaterally blind/hemianopia",
                "4 Facial palsy (can use grimace) (0–3): 0 normal; 1 minor; 2 partial (lower face); 3 complete (no upper/lower movement).",
                "5 Motor arm L/R (each 0–4): 0 no drift; 1 drift; 2 some effort vs gravity; 3 no effort vs gravity; 4 no movement.",
                "6 Motor leg L/R (each 0–4): 0 no drift; 1 drift; 2 some effort vs gravity; 3 no effort vs gravity; 4 no movement.",
                "7 Limb Ataxia (F2N/H2S) (0–2): 0 absent; 1 present in one limb; 2 present in two limbs.",
                "8 Sensory (0–2): 0 normal; 1 mild/moderate loss; 2 severe/total loss.",
                "9 Best language (describe, name items, read) (0–3): 0 none; 1 mild/moderate aphasia; 2 severe aphasia; 3 mute/global aphasia.",
                "10 Dysarthria (0–2): 0 normal; 1 mild/moderate; 2 severe/unintelligible or anarthric (UN if intubated/physical barrier).",
                "11 Extinction/inattention (0–2): 0 none; 1 extinction/inattention in one modality; 2 profound or >1 modality.",
            ],
            "cautions": "NIHSS can under-represent posterior circulation syndromes; document specific disabling deficits separately.",
        },

        {
            "name": "IV thrombolysis (alteplase / tenecteplase) — core eligibility & dosing",
            "item_type": "procedure",
            "steps": [
                "Core eligibility (typical): disabling ischemic stroke symptoms + treatable within 4.5 hours of last-known-well (or wake-up/unknown onset with appropriate imaging).",
                "Only blood glucose must precede IV thrombolysis; other labs/tests should not delay treatment unless anticoagulant use or concern for abnormality.",
            ],
        },

        {
            "name": "Thrombolysis contraindications (IV fibrinolytic) — typical AHA/ASA-based checklist",
            "item_type": "procedure",
            "summary": "Use your local inclusion/exclusion checklist; this is a commonly used operational list (absolute vs relative).",
            "steps": [
                "ABSOLUTE / DO NOT GIVE (typical):",
                "- Intracranial hemorrhage on CT or suspected SAH.",
                "- Extensive established infarct on CT (e.g., clear hypoattenuation >1/3 MCA territory).",
                "- Unable to maintain BP <185/110 despite treatment.",
                "- Ischemic stroke within the last 3 months.",
                "- History of intracranial hemorrhage.",
                "- Severe head trauma within the last 3 months.",
                "- Active internal bleeding (including suspected aortic dissection).",
                "- Arterial puncture at a non-compressible site within the last 7 days.",
                "- Infective endocarditis.",
                "- GI bleeding within last 21 days or structural GI malignancy.",
                "- Intracranial or spinal surgery within last 3 months.",
                "- Labs: glucose <50 mg/dL (treat first; if deficits persist after normalization, re-evaluate).",
                "- Labs (if indicated/known): INR >1.7; platelets <100,000; PT >15 sec; aPTT >40 sec.",
                "- Meds: full-dose LMWH within last 24 hours (prophylactic-dose LMWH is not an exclusion in many protocols).",
                "- Meds: DOAC ingestion within last 48 hours (assuming normal renal function) unless protocol allows drug-specific testing showing no clinically relevant activity.",
                "",
                "RELATIVE / DISCUSS WITH STROKE EXPERT (examples commonly used operationally):",
                "- Stroke too mild AND non-disabling (mild nondisabling deficits are generally not treated).",
                "- Prior IV/IA thrombolysis or thrombectomy at outside facility before arrival.",
                "- Major surgery or major trauma within 14 days (non-head).",
                "- Seizure at onset with postictal deficits and no evidence of stroke (consider imaging/clinical context).",
                "- MI within last 3 months; acute pericarditis.",
                "- Lumbar puncture within 7 days.",
                "- Past GI/GU bleeding history.",
                "- Pregnancy (case-by-case; risk/benefit).",
                "- Known intracranial lesion with higher bleeding risk (e.g., AVM, intracranial tumor; some protocols treat aneurysm >10 mm as higher risk).",
                "- Severe hyperglycemia >400 mg/dL (treat; if deficits persist after normalization, re-evaluate).",
            ],
        },

        {
            "name": "Blood pressure control (AIS reperfusion-focused)",
            "item_type": "procedure",
            "steps": [
                "If IV thrombolysis candidate: lower BP to <185/110 before bolus; maintain <180/105 for 24 hours after treatment.",
                "If mechanical thrombectomy planned and no IV lytic given: many pathways target ≤185/110 pre-procedure (double-check).",
                "If NOT a reperfusion candidate: permissive HTN is commonly allowed up to ~220/120 if no other indication to treat.",
                "If hemorrhage: BP goal < 160/110 is often recommended (double check)",
            ],
        },
    ],
},
}
