from typing import Dict, List, Tuple

MED_POINT_FIELDS: List[Tuple[str, str]] = [
    ("dose", "Dose"),
    ("onset_peak_duration", "Pharmacokinetics"),
    ("mechanism", "Mechanism"),
    ("contra", "Contraindications / cautions"),
    ("side_effects", "Side effects"),
    ("fun_fact", "Fun fact"),
]

RRT_MED_GUIDE: Dict[str, Dict[str, object]] = {
    "Bradycardia": {
        "medications": [
            {
                "name": "Atropine",
                "item_type": "medication",
                "dose": "1 mg IV bolus every 3-5 minutes; max cumulative dose 3 mg.",
                "onset_peak_duration": "Onset 1 minute; peak 2-4 minutes; duration 30-60 minutes.",
                "mechanism": "Antimuscarinic (vagolytic): blocks cardiac muscarinic receptors, which increases SA node firing and AV nodal conduction; minimal direct contractility effect.",
                "contra": "May worsen Mobitz II or CHB with wide QRS. Contraindicated after cardiac transplant (asystole). Use caution in acute coronary syndrome.",
                "fun_fact": "The name comes from Atropa belladonna (Nightshade); Belladonna named because Cleopatra used the eye drops for pupil dilation as a beauty product.",
            },
            {
                "name": "Temporary pacing (transcutaneous/transvenous)",
                "item_type": "procedure",
                "summary": "Start transcutaneous pacing immediately while preparing medications.",
                "steps": [
                    "Set a backup rate (commonly 60-80/min), then increase mA until electrical capture is seen.",
                    "Confirm mechanical capture with pulse/BP or bedside ultrasound, not ECG alone.",
                    "If transcutaneous capture is unreliable or prolonged support is needed, escalate to transvenous pacing.",
                ],
                "cautions": "Pain and muscle contraction are common; provide analgesia/sedation when blood pressure allows. Re-check capture frequently.",
            },
            {
                "name": "Epinephrine infusion",
                "item_type": "medication",
                "dose": "2-10 mcg/min IV infusion; in peri-arrest some teams start at 10 mcg/min and then down-titrate.",
                "onset_peak_duration": "Onset under 1 minute; peak effect within minutes; duration is brief and highly titratable while running.",
                "mechanism": "Alpha and beta agonist: acts on the whole heart, unlike atropine, making it more likely to be successful.",
                "contra": "None.",
                "comments": "If epinephrine not available, put a vial of cardiac epinephrine in 1L NS, mix the bag, and run it at 120 mL/hr - 600 ml/hr to approximate 2-10 mcg/min.",
            },
            {
                "name": "Calcium",
                "item_type": "medication",
                "dose": "1g CaCl (CVC) or 3g CaGluc (PIV). If HyperK can consider redosing. iSTAT might be helpful.",
                "comments": "Calcium-responsive bradycardias: HyperK, HypoCa, HyperMg, CCB, BB",
            },
        ],
    },
    "Cardiac": {
        "medications": [
            {
                "name": "Vagal maneuvers (stable regular narrow-complex SVT)",
                "item_type": "procedure",
                "summary": "Best first maneuver is the modified Valsalva. Use only in a hemodynamically stable patient with likely regular narrow-complex re-entrant SVT.",
                "steps": [
                    "Modified Valsalva (best first): start semi-recumbent at about 45 degrees. Have the patient generate about 40 mm Hg of pressure for 15 seconds (for example by forcefully blowing into a syringe or manometer). Immediately lay the patient flat and passively raise the legs to about 45 degrees for 15 seconds, then return to the semi-recumbent position and reassess rhythm after about 45 seconds.",
                    "The modified technique is meaningfully more effective than the standard seated/semi-recumbent Valsalva and is a good first attempt while IV access, pads, and adenosine are being prepared.",
                    "Standard Valsalva: if the modified version is not feasible, use a firm 15-second strain against a closed glottis or pressure target, but expect lower conversion rates.",
                    "Carotid sinus massage is a backup option only: one side at a time with continuous ECG monitoring, gentle pressure over the carotid sinus for about 5-10 seconds, then reassess before considering the other side. Never massage both sides simultaneously.",
                    "Cold facial stimulus / diving reflex is mainly a pediatric or occasional fallback maneuver; in adults it is generally less useful than modified Valsalva.",
                ],
                "cautions": "Do not use vagal maneuvers as a delay tactic in unstable tachycardia. Avoid carotid massage with carotid bruit, known significant carotid disease, or recent TIA/stroke; many protocols also avoid it after recent MI, VF, or VT.",
            },
            {
                "name": "Synchronized cardioversion (DCCV)",
                "item_type": "procedure",
                "summary": "Use for tachycardia with serious signs/symptoms caused by the rhythm. Sedate whenever feasible, but do not delay if the patient is crashing.",
                "steps": [
                    "Place pads, attach monitor/defibrillator, establish IV access, and have suction/airway equipment ready.",
                    "Turn SYNC on and confirm the device is marking each QRS/R wave before delivering the shock.",
                    "Use current AHA starting energies: atrial fibrillation 200 J, atrial flutter 200 J, regular narrow-complex tachycardia 100 J, monomorphic VT with a pulse 100 J.",
                    "If the first attempt fails, escalate energy per device/patient response and remember many defibrillators require you to re-enable synchronization after each shock.",
                    "If synchronization is not possible and the patient is critically unstable, move to unsynchronized shock.",
                ],
                "cautions": "Do not use synchronized cardioversion for polymorphic VT, VF, or pulseless VT. Shock delivery may be delayed if the monitor cannot synchronize reliably.",
            },
            {
                "name": "Defibrillation (unsynchronized shock)",
                "item_type": "procedure",
                "summary": "Use for VF, pulseless VT, and polymorphic VT; in a crashing unstable tachyarrhythmia, use if synchronization cannot be achieved fast enough.",
                "steps": [
                    "Turn SYNC off before shocking. Charge while CPR continues when appropriate, then clear and shock with minimal interruption.",
                    "Adult biphasic defibrillation: use the manufacturer recommendation (commonly 120-200 J initial); if unknown, use the maximum available setting.",
                    "Adult monophasic defibrillation: 360 J.",
                    "After the shock, resume CPR immediately for 2 minutes before the next rhythm check if the patient is pulseless.",
                    "Second and later biphasic shocks should be equivalent or higher energy per device guidance.",
                ],
                "cautions": "Do not pause to check a pulse or rhythm for long after a shock in cardiac arrest; prioritize immediate chest compressions.",
            },
            {
                "name": "Transcutaneous pacing",
                "item_type": "procedure",
                "summary": "Use for symptomatic bradycardia when atropine is ineffective or unlikely to work; prepare for transvenous pacing if capture is unreliable or prolonged support is expected.",
                "steps": [
                    "Place pacing/defibrillation pads, attach monitor, and provide analgesia/sedation if blood pressure allows because pacing is painful.",
                    "Set a pacing rate, commonly 60-80/min.",
                    "Increase current (mA) until electrical capture appears on the monitor, then confirm mechanical capture with a pulse, blood pressure, or bedside ultrasound - not ECG alone.",
                    "Set the output slightly above the capture threshold and reassess capture frequently because it can be lost with movement or pad issues.",
                    "While pacing, continue to correct reversible causes and prepare dopamine/epinephrine infusion or transvenous pacing when indicated.",
                ],
                "cautions": "Electrical spikes alone do not prove effective perfusion. If the patient remains unstable despite apparent capture, reassess immediately.",
            },
        ],
    },
    "Active Ongoing Seizure": {
        "medications": [
            {
                "name": "Lorazepam",
                "item_type": "medication",
                "dose": "4 mg IV over 2 minutes; may repeat once in 5-10 minutes. 0.1 mg/kg, maximum rate 2 mg/min is also okay.",
                "onset_peak_duration": "Onset 1-3 minutes IV; peak 5-15 minutes; anticonvulsant effect usually several hours.",
            },
            {
                "name": "Midazolam (if no IV)",
                "item_type": "medication",
                "dose": "10 mg IM once (or 10 mg IN/IV).",
                "onset_peak_duration": "IM onset about 5-10 minutes (faster IV/IN).",
            },
            {
                "name": "Levetiracetam",
                "item_type": "medication",
                "dose": "If seizures still present, give 60 mg/kg, max 4500 mg, infuse over 10 minutes.",
                "comments": "Give it whenever it arrives but move on to next steps.",
            },
            {
                "name": "D50",
                "item_type": "medication",
                "comments": "Don't forget to check glucose",
            },
            {
                "name": "Hypertonic sodium bicarbonate",
                "item_type": "medication",
                "dose": "2 ampules (100 mEq) of 1 mEq/ml concentration",
                "comments": "Hyponatremia is an uncommon cause of seizures but needs immediate treatment if present",
            },
            {
                "name": "Thiamine",
                "item_type": "medication",
                "comments": "Known cause of seizures. When in doubt. OK to give.",
            },
            {
                "name": "Ketamine",
                "item_type": "medication",
                "dose": "1 mg/kg slow IV push over 2 minutes",
                "comments": "When you are thinking about ketamine you are in intubation territory. Call for propofol gtt or midazolam bolus + gtt, paralytic, and norepinephrine",
            },
        ],
    },
    "Neuro Exams": {
        "medications": [
            {
                "name": "HINTS exam (acute vestibular syndrome only)",
                "item_type": "procedure",
                "summary": "Use only in a currently symptomatic patient with continuous acute vestibular syndrome (ongoing vertigo/dizziness, spontaneous nystagmus, nausea/vomiting, gait unsteadiness).",
                "steps": [
                    "Do not use HINTS for episodic dizziness, clearly triggered positional dizziness, or a patient who is no longer symptomatic at the time of exam.",
                    "Head impulse: ask patient to fix on your nose and deliver small rapid head turns. An abnormal corrective saccade suggests peripheral vestibulopathy; a normal head impulse in acute vestibular syndrome is a central red flag.",
                    "Nystagmus: look in primary gaze and with lateral gaze. Unidirectional horizontal nystagmus favors peripheral disease; direction-changing, vertical, or torsional nystagmus favors central pathology.",
                    "Test of skew: alternate cover each eye while patient fixes on a target. Vertical realignment after uncovering is concerning for a central lesion.",
                    "HINTS is concerning for stroke if any one central sign is present. New unilateral hearing loss (HINTS+) also raises concern for central ischemia, especially AICA territory.",
                ],
                "cautions": "A dangerous HINTS can outperform early MRI in expert hands, but misuse is common. If concern for posterior circulation stroke remains high, treat it as stroke regardless of a reassuring bedside exam.",
            },
            {
                "name": "Dix-Hallpike maneuver (posterior canal BPPV)",
                "item_type": "procedure",
                "summary": "Use for brief, triggered positional vertigo when posterior canal BPPV is suspected; do not use it as a substitute for HINTS in continuous acute vestibular syndrome.",
                "steps": [
                    "Start seated. Turn the head 45 degrees toward the side being tested, then bring the patient quickly to supine with the head hanging about 20 degrees below horizontal and the tested ear down.",
                    "Watch the eyes and ask about vertigo for at least 30 seconds after positioning.",
                    "A positive test for posterior canal BPPV is reproduction of vertigo with classic torsional, upbeating nystagmus when the affected ear is down.",
                    "Repeat on the opposite side if the first side is negative.",
                    "If the maneuver causes horizontal nystagmus or symptoms are strongly suggestive but Dix-Hallpike is negative, consider lateral canal BPPV and perform a supine roll test.",
                ],
                "cautions": "Use caution or a modified maneuver in patients with significant cervical spine disease, severe back pain, vascular instability, or limited neck extension.",
            },
            {
                "name": "Meningitis bedside exam",
                "item_type": "procedure",
                "summary": "Look for meningeal irritation and encephalopathy, but do not rely on bedside signs alone to rule meningitis in or out.",
                "steps": [
                    "Screen for the syndrome first: fever, headache, neck pain/stiffness, photophobia, vomiting, altered mental status, seizure, petechial/purpuric rash, and immunocompromise.",
                    "Assess nuchal rigidity with gentle passive neck flexion; resistance or pain supports meningeal irritation.",
                    "Brudzinski sign: passive neck flexion causing involuntary hip/knee flexion suggests meningeal irritation.",
                    "Kernig sign: with hip and knee flexed to 90 degrees, pain/resistance on knee extension suggests meningeal irritation.",
                    "Perform a focused neuro exam for focal deficits, cranial neuropathies, papilledema, or markedly depressed mental status, which raise concern for encephalitis, mass effect, or elevated ICP.",
                ],
                "cautions": "Classic meningeal signs have limited sensitivity. Their absence does not exclude bacterial meningitis, especially in older, immunocompromised, or altered patients.",
            },
            {
                "name": "Intubated neuro exam",
                "item_type": "procedure",
                "summary": "Use a structured exam and document confounders; the FOUR score is often more useful than GCS when the patient is intubated.",
                "steps": [
                    "Before interpreting the exam, document sedatives, analgesics, paralytics, hypothermia, severe metabolic derangements, and whether a sedation pause is safe.",
                    "Check pupils first: size, symmetry, and reactivity. Then assess gaze position, spontaneous eye opening, tracking, and any gaze deviation.",
                    "Assess motor response to voice and to central/peripheral painful stimulus: localizing, withdrawing, extensor/flexor posturing, flaccidity, and any asymmetry.",
                    "Check brainstem reflexes when relevant: corneal reflexes, cough with suctioning, and gag if it will change management.",
                    "Assess respiratory drive and vent interaction: breathing above the set rate, triggering the ventilator, or absent spontaneous effort.",
                    "Trend the same structured exam over time and document the best response, laterality, and any change from prior exam.",
                ],
                "cautions": "Do not overcall absent responses while paralytics or deep sedation are active. New asymmetry, loss of brainstem reflexes, or worsening exam should prompt urgent escalation.",
            },
        ],
    },
    "Rheumatologic Exam": {
        "medications": [
            {
                "name": "Rheumatoid arthritis - classic findings",
                "item_type": "procedure",
                "summary": "Think inflammatory symmetric small-joint disease.",
                "steps": [
                    "Inspect and palpate MCP, PIP, and wrists for symmetric boggy synovitis, warmth, tenderness, and reduced ROM.",
                    "Typical chronic deformities: ulnar deviation at MCPs, swan-neck deformities, boutonniere deformities, and volar subluxation.",
                    "Look for rheumatoid nodules over extensor surfaces/olecranon.",
                    "History/exam clues that fit: prolonged morning stiffness and hand squeeze pain.",
                ],
                "cautions": "Early RA may present before fixed deformities develop; absence of deformity does not exclude active inflammatory arthritis.",
            },
            {
                "name": "Systemic lupus erythematosus - classic findings",
                "item_type": "procedure",
                "summary": "Look for mucocutaneous findings plus nonerosive inflammatory arthritis.",
                "steps": [
                    "Inspect for malar rash over cheeks/nasal bridge that classically spares the nasolabial folds.",
                    "Look for oral or nasal ulcers, non-scarring alopecia, and photosensitive rash.",
                    "Examine hands for tender/swollen joints, usually nonerosive and often involving small joints.",
                    "Check for serositis clues on exam/history: pleuritic chest pain or pericarditic features.",
                ],
                "cautions": "SLE is multisystem; skin findings may be absent at presentation.",
            },
            {
                "name": "Dermatomyositis - classic findings",
                "item_type": "procedure",
                "summary": "Pair proximal weakness with characteristic skin disease.",
                "steps": [
                    "Test proximal strength: difficulty rising from a chair, climbing stairs, or combing hair suggests proximal muscle weakness.",
                    "Inspect eyelids for heliotrope rash and hands for Gottron papules/sign over MCP/PIP/extensor surfaces.",
                    "Look for shawl sign or V-sign photodistributed erythema.",
                    "Check for mechanic's hands if antisynthetase-spectrum disease is on the differential.",
                ],
                "cautions": "Normal distal strength does not rule out inflammatory myopathy; focus on proximal groups and skin clues.",
            },
            {
                "name": "Systemic sclerosis - classic findings",
                "item_type": "procedure",
                "summary": "Skin thickening, vascular findings, and fingertip injury are the big bedside clues.",
                "steps": [
                    "Look for puffy fingers early and sclerodactyly later; assess whether skin thickening extends proximal to the MCPs.",
                    "Inspect fingertips for digital pitting, ulcers, or loss of pulp.",
                    "Look for telangiectasias and ask about/observe Raynaud phenomenon.",
                    "Check nailfold capillaries if available and note microstomia or mask-like facies in advanced disease.",
                ],
                "cautions": "Diffuse skin thickening proximal to the MCPs is especially concerning for systemic sclerosis.",
            },
            {
                "name": "Psoriatic arthritis - classic findings",
                "item_type": "procedure",
                "summary": "Think psoriasis, nails, dactylitis, DIP disease, and enthesitis.",
                "steps": [
                    "Inspect skin and scalp for psoriasis; do not forget hidden areas such as gluteal cleft, umbilicus, and behind ears.",
                    "Look at nails for pitting, onycholysis, and dystrophy.",
                    "Examine for dactylitis ('sausage digit') and tenderness at entheses such as Achilles or plantar fascia insertion.",
                    "Check for DIP-predominant arthritis or asymmetric oligoarthritis.",
                ],
                "cautions": "Psoriasis may be subtle or historical; nail disease and dactylitis are especially useful bedside clues.",
            },
            {
                "name": "Gout - classic findings",
                "item_type": "procedure",
                "summary": "Sudden, exquisitely painful monoarthritis is the bedside pattern.",
                "steps": [
                    "Look for podagra: abrupt onset red, hot, swollen, exquisitely tender first MTP arthritis.",
                    "Assess whether the pain peaked rapidly (often within 24 hours) and whether even light touch is intolerable.",
                    "Inspect for tophi at ears, olecranon bursae, fingers, toes, prepatellar area, or Achilles region.",
                    "Remember gout can also involve ankle, midfoot, knee, wrist, or olecranon bursa.",
                ],
                "cautions": "Classic exam supports gout, but septic arthritis still has to be excluded in an acutely inflamed joint.",
            },
            {
                "name": "Giant cell arteritis / polymyalgia rheumatica - classic findings",
                "item_type": "procedure",
                "summary": "In older adults, combine cranial ischemic symptoms with vascular exam and shoulder/hip girdle stiffness.",
                "steps": [
                    "Palpate temporal arteries for tenderness, nodularity, thickening, or reduced pulsation.",
                    "Ask specifically about new temporal headache, scalp tenderness, jaw claudication, and transient or permanent visual symptoms.",
                    "For PMR features, assess painful restricted active shoulder motion and marked morning stiffness in shoulders/neck/hips.",
                    "If vision symptoms or strong GCA features are present, escalate immediately rather than waiting for confirmatory testing.",
                ],
                "cautions": "A normal temporal artery exam does not exclude GCA.",
            },
        ],
    },
    "Skin Exam": {
        "medications": [
            {
                "name": "General skin exam approach",
                "item_type": "procedure",
                "summary": "Describe lesions before naming them.",
                "steps": [
                    "Expose the involved area fully and, when relevant, examine the entire skin surface including scalp, nails, mucosa, palms, soles, and intertriginous areas.",
                    "Describe morphology first: macule/patch, papule/plaque, vesicle/bulla, pustule, nodule, wheal, crust, scale, erosion, or ulcer.",
                    "Then describe distribution and arrangement: localized vs generalized, symmetric vs asymmetric, flexural vs extensor, dermatomal, acral, photo-distributed, annular, linear, grouped, or targetoid.",
                    "Palpate for warmth, tenderness, induration, fluctuance, skin fragility, blanching, and whether scale or crust lifts easily.",
                ],
                "cautions": "A complete skin exam can reveal important incidental findings, including hidden infection and skin cancer.",
            },
            {
                "name": "Psoriasis - classic findings",
                "item_type": "procedure",
                "summary": "Well-demarcated plaques with scale on extensor surfaces.",
                "steps": [
                    "Look for sharply demarcated erythematous plaques with thick silvery scale on elbows, knees, scalp, lower back, or gluteal cleft.",
                    "Check nails for pitting, onycholysis, subungual hyperkeratosis, or oil-drop discoloration.",
                    "Auspitz sign and Koebner phenomenon are classic clues, though not required for diagnosis.",
                ],
                "cautions": "Psoriasis can involve scalp, nails, genitals, and intertriginous areas with less obvious scale.",
            },
            {
                "name": "Atopic dermatitis - classic findings",
                "item_type": "procedure",
                "summary": "The 'itch that rashes': dry, itchy, eczematous skin.",
                "steps": [
                    "Look for xerosis, excoriations, erythematous or hyperpigmented patches/plaques, and chronic lichenification.",
                    "In older children and adults, flexural involvement is classic: antecubital fossae, popliteal fossae, neck, wrists, and hands.",
                    "Ask about personal or family history of atopy and whether itch preceded the visible rash.",
                ],
                "cautions": "Secondary infection is common; crusting, oozing, or punched-out erosions should lower your threshold to consider superinfection.",
            },
            {
                "name": "Scabies - classic findings",
                "item_type": "procedure",
                "summary": "Intensely pruritic eruption with characteristic distribution and burrows.",
                "steps": [
                    "Look for small papules, vesicles, excoriations, and short thin burrows in finger webs, wrists, elbows, axillae, belt line, groin, buttocks, penis, and around the nipples.",
                    "Nighttime itch and symptomatic close contacts are classic historical clues.",
                    "In infants or immunocompromised patients, the eruption can be more widespread and involve scalp, palms, or soles.",
                ],
                "cautions": "Adults usually do not have lesions above the neck; crusted scabies can look very different and carry a high mite burden.",
            },
            {
                "name": "Herpes zoster - classic findings",
                "item_type": "procedure",
                "summary": "Painful unilateral dermatomal vesicles.",
                "steps": [
                    "Ask about pain, burning, tingling, or allodynia preceding the rash.",
                    "Look for grouped vesicles on an erythematous base in one or two adjacent dermatomes.",
                    "The rash classically does not cross the midline; thoracic and trigeminal distributions are common.",
                ],
                "cautions": "Atypical or disseminated presentations are more likely in immunocompromised patients.",
            },
            {
                "name": "Targetoid and sloughing eruptions - classic findings",
                "item_type": "procedure",
                "summary": "Recognize true target lesions and dangerous mucosal disease.",
                "steps": [
                    "Erythema multiforme classically shows symmetric target lesions with three zones, often on extensor extremities, palms, or soles.",
                    "Stevens-Johnson syndrome / TEN should be suspected with painful dusky or purpuric macules, mucosal involvement, bullae, epidermal detachment, or positive Nikolsky-type skin fragility.",
                    "Recent high-risk medication exposure and systemic symptoms increase concern for severe cutaneous adverse reaction.",
                ],
                "cautions": "Painful skin, mucosal erosions, and skin sloughing are red flags and need urgent escalation.",
            },
            {
                "name": "Skin cancer warning lesions - classic findings",
                "item_type": "procedure",
                "summary": "Use the ABCDEs for melanoma and recognize common nonmelanoma patterns.",
                "steps": [
                    "Melanoma warning features: asymmetry, irregular border, color variegation, diameter often greater than 6 mm, and evolving change.",
                    "Basal cell carcinoma often looks pearly, shiny, translucent, telangiectatic, ulcerated, or like a sore that heals and returns.",
                    "Squamous cell carcinoma often appears as a firm hyperkeratotic papule/plaque/nodule, sometimes crusted or ulcerated.",
                ],
                "cautions": "Any lesion that is changing, bleeding, or not healing deserves attention even if it does not fit a textbook pattern.",
            },
        ],
    },
    "Anaphylaxis": {
        "medications": [
            {
                "name": "Immediate actions",
                "item_type": "procedure",
                "steps": [
                    "Ask patient to speak their name to assess for stridor. If stridor, prepare to establish an airway.",
                    "All steps happen simultaneously, including the below actions, epinephrine, and airway management.",
                    "Stop any infusions. Establish IV/IO access.",
                    "Give HFNC or NRB, place on monitor, and establish IV/IO access.",
                    "Lay patient supine with legs elevated (or left lateral if vomiting/pregnant); avoid sudden upright posture (empty ventricle syndrome)",
                    "Give epinephrine at the earliest opportunity. (Better outcomes)",
                    "Give 1-2L rapid fluids ASAP.",
                    "Rapid airway assessment and get the most experienced intubator around, prepare for emergency cricothyrotomy and have an extraglottic backup.",
                    "Check serum tryptase in addition to normal labs",
                ],
                "cautions": "Skin findings can be absent in severe reactions; treat airway/breathing/circulation compromise as anaphylaxis.",
            },
            {
                "name": "Emergency cricothyrotomy (CICO rescue airway)",
                "item_type": "procedure",
                "summary": "If cannot intubate/cannot oxygenate with worsening hypoxemia, move early to front-of-neck access.",
                "steps": [
                    "Landmarks (laryngeal handshake): palpate hyoid, thyroid cartilage, then cricothyroid membrane (CTM) between thyroid and cricoid; stabilize the larynx with non-dominant hand.",
                    "Equipment: #10 (or similarly wide) scalpel, bougie (coudé tip), suction, and a lubricated cuffed tube (often size 6.0).",
                    "If CTM palpable: make a transverse stab through skin + CTM, rotate blade 90 degrees with sharp edge caudad, and use the blade as a hook to keep the opening patent.",
                    "If CTM impalpable: make a large vertical midline skin incision, use blunt finger dissection to identify/stabilize laryngeal structures, then perform the transverse CTM stab.",
                    "Advance bougie gently into trachea along the blade/finger track; it should pass without fixed resistance. If resistance is met, do not force - withdraw slightly and redirect.",
                    "Railroad a lubricated cuffed tracheostomy tube (or a 6.0 cuffed ETT per local kit) over the bougie into the trachea, then remove bougie.",
                    "Inflate cuff, ventilate, confirm with continuous waveform capnography + chest rise, and secure tube.",
                ],
                "cautions": "Last-resort airway procedure. Keep oxygen delivery attempts ongoing during setup and follow local difficult-airway protocol.",
            },
            {
                "name": "Epinephrine (IM) - first line",
                "item_type": "medication",
                "dose": "0.5 mg IM (0.5 mL of 1 mg/mL [1:1000]) into anterolateral thigh; repeat every 5 minutes as needed.",
                "mechanism": "Alpha-1 vasoconstriction reduces edema/hypotension, beta-1 supports cardiac output, and beta-2 bronchodilates/reduces mediator release.",
            },
            {
                "name": "Epinephrine infusion (refractory symptoms)",
                "item_type": "medication",
                "dose": "If persistent respiratory/circulatory compromise after 2 IM doses + fluids, start IV epinephrine infusion (e.g., 0.05-0.1 mcg/kg/min and titrate).",
            },
            {
                "name": "Nebulized albuterol (salbutamol)",
                "item_type": "medication",
                "dose": "5 mg nebulized for persistent bronchospasm/wheezing after epinephrine.",
                "comments": "Adjunct only; never replace epinephrine with bronchodilator alone.",
            },
            {
                "name": "Glucagon (beta-blocker use, refractory hypotension/bradycardia)",
                "item_type": "medication",
                "dose": "1 to 5 mg IV over 5 minutes, then infusion 5-15 mcg/min if needed.",
                "mechanism": "Improves inotropy/chronotropy via non-beta receptor pathway.",
            },
            {
                "name": "Antihistamines and corticosteroids (adjuncts only)",
                "item_type": "medication",
                "dose": "Consider only after stabilization, mainly for persistent skin symptoms or refractory/protracted reaction per protocol.",
                "mechanism": "May improve cutaneous symptoms; delayed onset.",
            },
            {
                "name": "Observation and disposition",
                "item_type": "procedure",
                "steps": [
                    "Observe for biphasic recurrence based on severity/risk factors and local protocol.",
                    "AEdit allergy list",
                ],
            },
        ],
    },
    "Code Stroke": {
    "medications": [
        {
            "name": "Immediate steps",
            "item_type": "procedure",
            "steps": [
                "Check fingerstick glucose (treat hypoglycemia first before continuing).",
                "Determine Last Known Well (clock time), onset pattern (sudden vs stuttering), wake-up/unknown onset, and any seizure at onset.",
                "Determine baseline functional status and pre-stroke mRS (modified Rankin Scale)",
                "Focused neuro exam + NIHSS + disabling deficits.",
                "Establish IV access. Obtain weight for thrombolytic dosing.",
                "Draw labs (do not delay imaging): CBC, CMP, PT/INR, aPTT; troponin; pregnancy test if applicable.",
                "Baseline ECG and troponin are recommended but should NOT delay IV thrombolysis if otherwise eligible.",
                "Review meds (anticoagulants/antiplatelets), bleeding history, recent stroke/head trauma/surgery, and BP control feasibility.",
            ],
        },
        {
            "name": "LVO patterns (clinical clues)",
            "item_type": "procedure",
            "steps": [
                "Anterior circulation clues: forced gaze deviation, aphasia, neglect, homonymous field cut, dense unilateral weakness.",
                "Posterior circulation clues: depressed consciousness, diplopia, dysarthria, ataxia, 'crossed' deficits; consider basilar occlusion even with modest NIHSS.",
                "If high suspicion for LVO → CTA head/neck early; do not rely on NIHSS alone.",
            ],
        },

        {
            "name": "NIHSS (0–42)",
            "item_type": "procedure",
            "summary": "Perform early (baseline). Recheck with clinical changes.",
            "steps": [
                "1a LOC (0–3): 0 alert; 1 arousable to minor stimulation; 2 needs repeated/strong stimulation; 3 unresponsive/flaccid.",
                "1b Month + Age (0–2): 0 both correct; 1 one correct; 2 neither.",
                "1c 'Blink eyes' + 'Squeeze hands' (0–2): 0 both; 1 one; 2 neither.",
                "2 Horizontal gaze (0–2): 0 normal; 1 partial gaze palsy; 2 forced deviation/complete palsy not overcome by oculocephalic maneuver.",
                "3 Visual fields (0–3): 0 none; 1 partial hemianopia; 2 complete hemianopia; 3 bilaterally blind/hemianopia",
                "4 Facial palsy (can use grimace) (0–3): 0 normal; 1 minor; 2 partial (lower face); 3 complete (no upper/lower movement).",
                "5 Motor arm L/R (each 0–4): 0 no drift; 1 drift; 2 some effort vs gravity; 3 no effort vs gravity; 4 no movement.",
                "6 Motor leg L/R (each 0–4): 0 no drift; 1 drift; 2 some effort vs gravity; 3 no effort vs gravity; 4 no movement.",
                "7 Limb Ataxia (F2N/H2S) (0–2): 0 absent; 1 present in one limb; 2 present in two limbs.",
                "8 Sensory (0–2): 0 normal; 1 mild/moderate loss; 2 severe/total loss.",
                "9 Best language (describe, name items, read) (0–3): 0 none; 1 mild/moderate aphasia; 2 severe aphasia; 3 mute/global aphasia.",
                "10 Dysarthria (0–2): 0 normal; 1 mild/moderate; 2 severe/unintelligible or anarthric (UN if intubated/physical barrier).",
                "11 Extinction/inattention (0–2): 0 none; 1 extinction/inattention in one modality; 2 profound or >1 modality.",
            ],
            "cautions": "NIHSS can under-represent posterior circulation syndromes; document specific disabling deficits separately.",
        },

        {
            "name": "IV thrombolysis (alteplase / tenecteplase) — core eligibility & dosing",
            "item_type": "procedure",
            "steps": [
                "Core eligibility (typical): disabling ischemic stroke symptoms + treatable within 4.5 hours of last-known-well (or wake-up/unknown onset with appropriate imaging).",
                "Only blood glucose must precede IV thrombolysis; other labs/tests should not delay treatment unless anticoagulant use or concern for abnormality.",
            ],
        },

        {
            "name": "Thrombolysis contraindications (IV fibrinolytic) — typical AHA/ASA-based checklist",
            "item_type": "procedure",
            "summary": "Use your local inclusion/exclusion checklist; this is a commonly used operational list (absolute vs relative).",
            "steps": [
                "ABSOLUTE / DO NOT GIVE (typical):",
                "- Intracranial hemorrhage on CT or suspected SAH.",
                "- Extensive established infarct on CT (e.g., clear hypoattenuation >1/3 MCA territory).",
                "- Unable to maintain BP <185/110 despite treatment.",
                "- Ischemic stroke within the last 3 months.",
                "- History of intracranial hemorrhage.",
                "- Severe head trauma within the last 3 months.",
                "- Active internal bleeding (including suspected aortic dissection).",
                "- Arterial puncture at a non-compressible site within the last 7 days.",
                "- Infective endocarditis.",
                "- GI bleeding within last 21 days or structural GI malignancy.",
                "- Intracranial or spinal surgery within last 3 months.",
                "- Labs: glucose <50 mg/dL (treat first; if deficits persist after normalization, re-evaluate).",
                "- Labs (if indicated/known): INR >1.7; platelets <100,000; PT >15 sec; aPTT >40 sec.",
                "- Meds: full-dose LMWH within last 24 hours (prophylactic-dose LMWH is not an exclusion in many protocols).",
                "- Meds: DOAC ingestion within last 48 hours (assuming normal renal function) unless protocol allows drug-specific testing showing no clinically relevant activity.",
                "",
                "RELATIVE / DISCUSS WITH STROKE EXPERT (examples commonly used operationally):",
                "- Stroke too mild AND non-disabling (mild nondisabling deficits are generally not treated).",
                "- Prior IV/IA thrombolysis or thrombectomy at outside facility before arrival.",
                "- Major surgery or major trauma within 14 days (non-head).",
                "- Seizure at onset with postictal deficits and no evidence of stroke (consider imaging/clinical context).",
                "- MI within last 3 months; acute pericarditis.",
                "- Lumbar puncture within 7 days.",
                "- Past GI/GU bleeding history.",
                "- Pregnancy (case-by-case; risk/benefit).",
                "- Known intracranial lesion with higher bleeding risk (e.g., AVM, intracranial tumor; some protocols treat aneurysm >10 mm as higher risk).",
                "- Severe hyperglycemia >400 mg/dL (treat; if deficits persist after normalization, re-evaluate).",
            ],
        },

        {
            "name": "Blood pressure control (AIS reperfusion-focused)",
            "item_type": "procedure",
            "steps": [
                "If IV thrombolysis candidate: lower BP to <185/110 before bolus; maintain <180/105 for 24 hours after treatment.",
                "If mechanical thrombectomy planned and no IV lytic given: many pathways target ≤185/110 pre-procedure (double-check).",
                "If NOT a reperfusion candidate: permissive HTN is commonly allowed up to ~220/120 if no other indication to treat.",
                "If hemorrhage: BP goal < 160/110 is often recommended (double check)",
            ],
        },
    ],
},
    "Rapid Sequence Intubation (RSI)": {
        "medications": [
            {
                "name": "Preparation",
                "item_type": "procedure",
                "summary": "Set up before pushing drugs. Once you paralyze, you are committed.",
                "steps": [
                    "Pre-oxygenate: NRB at flush rate or HFNC at 60 L/min for at least 3 minutes (goal is denitrogenation, not SpO2).",
                    "Apneic oxygenation: place nasal cannula at 15 L/min under the NRB/BVM and leave it running throughout the attempt.",
                    "Position: ramped/sniffing position with tragus of ear at level of sternal notch; elevate head of bed 20-30 degrees if hemodynamics allow.",
                    "Equipment at bedside: two working suctions, bougie, video laryngoscope + direct laryngoscope backup, cuffed ETT (typically 7.0-7.5 for women, 7.5-8.0 for men), 10 mL syringe for cuff, EtCO2 detector, ventilator.",
                    "Backup plan: extraglottic airway (LMA/iGel) immediately accessible; if CICO anticipated, have surgical airway kit open.",
                    "Have push-dose epinephrine drawn up (see post-intubation below).",
                ],
                "cautions": "The most dangerous moment is right after intubation when positive pressure + sedation + loss of sympathetic drive causes hypotension. Prepare for it.",
            },
            {
                "name": "Etomidate",
                "item_type": "medication",
                "dose": "0.3 mg/kg IV push.",
                "onset_peak_duration": "Onset 15-30 seconds; duration 5-15 minutes.",
                "mechanism": "GABA-A agonist. Hemodynamically neutral — does not cause significant hypotension or hypertension.",
                "contra": "Causes transient adrenal suppression (single dose is clinically insignificant in most patients). Avoid in septic shock if alternative available (debated). Can lower seizure threshold / cause myoclonus.",
                "fun_fact": "Most forgiving induction agent hemodynamically; good default when unsure.",
            },
            {
                "name": "Ketamine",
                "item_type": "medication",
                "dose": "1-2 mg/kg IV push (use 1-1.5 mg/kg in most adults).",
                "onset_peak_duration": "Onset 30-60 seconds; duration 10-20 minutes.",
                "mechanism": "NMDA antagonist. Sympathomimetic (releases catecholamines) — supports BP and HR. Bronchodilator.",
                "contra": "Previously listed as contraindicated in elevated ICP — this is outdated and no longer considered a contraindication. Use caution in severe uncontrolled hypertension or active psychosis.",
                "comments": "Best choice when hypotension, bronchospasm, or reactive airway disease is present. Provides analgesia in addition to sedation.",
            },
            {
                "name": "Propofol",
                "item_type": "medication",
                "dose": "1-2 mg/kg IV push (reduce to 0.5-1 mg/kg in elderly or hemodynamically fragile).",
                "onset_peak_duration": "Onset 15-30 seconds; duration 5-10 minutes.",
                "mechanism": "GABA-A agonist. Causes significant dose-dependent hypotension via vasodilation and myocardial depression.",
                "contra": "Avoid in hypotension or shock. Use only in hemodynamically stable patients or when hypotension is acceptable (e.g., hypertensive emergency). Soy/egg allergy is NOT a contraindication.",
                "comments": "Excellent for status epilepticus (anticonvulsant properties) and hypertensive patients. Have vasopressors ready.",
            },
            {
                "name": "Succinylcholine",
                "item_type": "medication",
                "dose": "1.5 mg/kg IV push (use ideal body weight in obesity for dosing).",
                "onset_peak_duration": "Onset 45-60 seconds; duration 6-10 minutes.",
                "mechanism": "Depolarizing neuromuscular blocker. Fastest onset of any paralytic.",
                "contra": "CONTRAINDICATED when hyperkalemia risk is elevated: burns >24 hours old, crush injuries >24 hours old, denervation injuries (stroke/spinal cord injury >72 hours), prolonged immobility/ICU myopathy, known hyperkalemia, muscular dystrophies, malignant hyperthermia history.",
                "comments": "Short duration is a double-edged sword: wears off quickly if you cannot intubate, but also wears off quickly if you can't ventilate. No reversal agent.",
            },
            {
                "name": "Rocuronium",
                "item_type": "medication",
                "dose": "1.2 mg/kg IV push for RSI-quality onset (lower doses give slower onset).",
                "onset_peak_duration": "Onset 45-60 seconds at RSI dose; duration 45-70 minutes.",
                "mechanism": "Non-depolarizing neuromuscular blocker (competitive acetylcholine antagonist at nicotinic receptor).",
                "contra": "No absolute contraindications. Preferred over succinylcholine when hyperkalemia risk exists.",
                "comments": "Reversible with sugammadex 16 mg/kg for immediate reversal. Long duration means if you fail the airway, you are managing it for ~1 hour. Always have a backup airway plan.",
            },
            {
                "name": "Post-intubation",
                "item_type": "procedure",
                "summary": "Confirm tube, start sedation, and anticipate hemodynamic crash.",
                "steps": [
                    "Confirm placement with continuous waveform capnography (gold standard). Auscultate. Secure tube and note depth at teeth (typically 21-23 cm).",
                    "Chest X-ray for tube position (tip 3-5 cm above carina).",
                    "Start sedation/analgesia immediately (paralysis without sedation is terrifying): propofol or midazolam gtt + fentanyl gtt, or ketamine gtt.",
                    "Initial vent settings (lung-protective): Vt 6-8 mL/kg IBW, RR 14-16, FiO2 100% initially and wean, PEEP 5.",
                    "Post-intubation hypotension: treat with push-dose epinephrine 10-20 mcg IV every 1-2 min (cardiac epi 100 mcg/mL diluted: 1 mL in 9 mL NS = 10 mcg/mL), IV fluid bolus, and start vasopressor infusion if not improving.",
                ],
                "cautions": "Post-intubation hypotension is extremely common and often multifactorial (loss of sympathetic tone, positive pressure ventilation reducing preload, sedation). Treat aggressively.",
            },
        ],
    },
    "Anticoagulant Reversal": {
        "medications": [
            {
                "name": "General approach",
                "item_type": "procedure",
                "summary": "Hold the anticoagulant. Determine severity. Reverse based on agent.",
                "steps": [
                    "Hold the anticoagulant and determine the drug, dose, and last ingestion time.",
                    "Classify bleed severity: life-threatening (ICH, hemodynamic instability, critical-site bleed) vs major vs minor. Life-threatening → immediate full reversal. Minor → may be able to hold drug and observe.",
                    "Labs: INR (warfarin), aPTT (heparin), anti-Xa level (LMWH, rivaroxaban, apixaban), thrombin time/dTT (dabigatran). Don't delay reversal waiting for results in a crashing patient.",
                    "Supportive: blood products (pRBC, platelets, FFP/cryo as indicated), direct pressure, procedural hemostasis, TXA 1g IV if not contraindicated.",
                ],
                "cautions": "Reversal agents carry thrombotic risk. Use the minimum reversal needed for the clinical situation. Minor bleeds on DOACs often do not require specific reversal.",
            },
            {
                "name": "Warfarin → 4-Factor PCC + Vitamin K",
                "item_type": "medication",
                "dose": "4F-PCC (Kcentra) dosed by INR: INR 2-4 → 25 units/kg; INR 4-6 → 35 units/kg; INR >6 → 50 units/kg. Max 5000 units. Give vitamin K 10 mg IV slow infusion (over 10-20 min) simultaneously.",
                "onset_peak_duration": "PCC onset within 10-15 minutes (factor replenishment is immediate). Vitamin K onset 4-6 hours (hepatic synthesis of new factors). PCC duration ~6-8 hours, vitamin K sustains correction beyond that.",
                "mechanism": "PCC provides factors II, VII, IX, X directly. Vitamin K enables endogenous synthesis to prevent rebound coagulopathy after PCC wears off.",
                "contra": "PCC carries thrombotic risk (DIC, DVT, PE, MI). Vitamin K IV has rare anaphylactoid risk — infuse slowly. Do NOT use FFP as first-line for life-threatening warfarin bleeds (too slow, volume overload, incomplete correction).",
                "comments": "Recheck INR 15-30 minutes after PCC. If still elevated, may need additional PCC or FFP. Always give vitamin K with PCC.",
            },
            {
                "name": "Dabigatran → Idarucizumab (Praxbind)",
                "item_type": "medication",
                "dose": "5 g IV total, given as two 2.5 g/50 mL vials infused or pushed consecutively.",
                "onset_peak_duration": "Onset within minutes; complete reversal of dabigatran anticoagulant effect. Duration ~24 hours.",
                "mechanism": "Humanized monoclonal antibody fragment that binds free and thrombin-bound dabigatran with 350x higher affinity than thrombin.",
                "contra": "None absolute. Use for life-threatening or uncontrolled bleeding or emergency surgery. If idarucizumab unavailable, 4F-PCC 50 units/kg is a fallback (less effective).",
                "comments": "Dabigatran is also dialyzable (useful if idarucizumab not available and patient has access). Check aPTT and thrombin time to assess residual dabigatran activity.",
            },
            {
                "name": "Rivaroxaban / Apixaban / Edoxaban → Andexanet alfa or 4F-PCC",
                "item_type": "medication",
                "dose": "Andexanet alfa (if available): low dose (apixaban ≤5 mg or rivaroxaban ≤10 mg or last dose >8 hrs ago) = 400 mg bolus then 4 mg/min x 2 hrs. High dose (apixaban >5 mg or rivaroxaban >10 mg and last dose ≤8 hrs ago) = 800 mg bolus then 8 mg/min x 2 hrs. If andexanet unavailable: 4F-PCC 50 units/kg IV (widely used, not FDA-approved for this indication but effective in practice).",
                "mechanism": "Andexanet is a recombinant modified factor Xa decoy that binds and sequesters Xa inhibitors. 4F-PCC provides clotting factors to overwhelm the anticoagulant effect.",
                "contra": "Andexanet carries thrombotic risk (~10% in trials) and is extremely expensive. 4F-PCC also carries thrombotic risk. Reserve for life-threatening bleeding.",
                "comments": "Many institutions do not stock andexanet due to cost and use 4F-PCC 50 units/kg as the default. Check anti-Xa levels to guide assessment. Rebound anticoagulation can occur after andexanet wears off.",
            },
            {
                "name": "Heparin (UFH) → Protamine",
                "item_type": "medication",
                "dose": "1 mg protamine per 100 units heparin remaining. Estimate based on last 2-3 hours of heparin infusion (heparin half-life ~60-90 min). Max single dose 50 mg. Give IV slow push over 10 minutes.",
                "onset_peak_duration": "Onset within 5 minutes. Duration ~2 hours.",
                "mechanism": "Positively charged protein that binds negatively charged heparin, forming an inactive complex.",
                "contra": "Anaphylactoid reactions, especially in patients with fish allergy, prior protamine exposure, or NPH insulin use. Causes hypotension if given too rapidly. Overdose of protamine is itself anticoagulant.",
            },
            {
                "name": "LMWH (enoxaparin) → Protamine (partial)",
                "item_type": "medication",
                "dose": "1 mg protamine per 1 mg enoxaparin if given within 8 hours. 0.5 mg protamine per 1 mg enoxaparin if 8-12 hours since dose. If >12 hours, protamine may not be needed. Max single dose 50 mg.",
                "mechanism": "Protamine neutralizes only the anti-IIa activity of LMWH, achieving ~60% reversal. Anti-Xa activity is only partially reversed.",
                "comments": "Protamine reversal of LMWH is incomplete. For life-threatening LMWH bleeds, also give 4F-PCC 50 units/kg or activated PCC (FEIBA) as adjunct, plus TXA.",
            },
        ],
    },
    "Acute Pulmonary Embolism": {
        "medications": [
            {
                "name": "Immediate actions",
                "item_type": "procedure",
                "summary": "Anticoagulate first. Assess hemodynamics. Do not delay heparin for imaging if clinical suspicion is high and the patient is deteriorating.",
                "steps": [
                    "If high clinical suspicion and hemodynamically unstable: give heparin bolus immediately, then image.",
                    "Assess hemodynamics: systolic BP, heart rate, signs of shock (altered mentation, mottled skin, lactate). This drives risk stratification.",
                    "Bedside echo (if available): look for RV dilation (RV:LV ratio >1:1 in apical 4-chamber), septal bowing into LV, McConnell sign (RV free wall akinesis with apical sparing).",
                    "Labs: troponin, BNP/NT-proBNP, lactate, CBC, BMP, coags, type and screen.",
                    "CTA chest is the confirmatory test. If too unstable for CT, bedside echo + clinical picture may be sufficient to treat.",
                    "Bilateral lower extremity DVU if PE confirmed (identifies clot burden and informs IVC filter discussion).",
                ],
                "cautions": "Do not delay anticoagulation waiting for imaging in a crashing patient with high suspicion. You can always stop heparin if the diagnosis is wrong.",
            },
            {
                "name": "Risk stratification",
                "item_type": "procedure",
                "summary": "Massive vs submassive vs low-risk determines treatment intensity.",
                "steps": [
                    "Massive PE: sustained hypotension (SBP <90 for ≥15 min or requiring pressors), cardiac arrest, or severe bradycardia with shock. → Systemic thrombolysis indicated.",
                    "Submassive PE: hemodynamically stable BUT with RV dysfunction (echo or CT) AND/OR elevated troponin/BNP. → Consider escalation (catheter-directed therapy, close monitoring in ICU, systemic lysis if deteriorating).",
                    "Low-risk PE: hemodynamically stable, no RV strain, normal biomarkers. → Anticoagulation alone, may not need ICU.",
                    "Watch for clinical deterioration in submassive PE — if BP drops or patient decompensates, escalate to massive PE protocol.",
                ],
            },
            {
                "name": "Heparin (unfractionated)",
                "item_type": "medication",
                "dose": "80 units/kg IV bolus (round to nearest 500 units, max ~10,000 units per some protocols), then 18 units/kg/hr infusion. Adjust to institutional aPTT nomogram (typical goal aPTT 60-80 seconds or anti-Xa 0.3-0.7).",
                "onset_peak_duration": "Onset immediate with IV bolus. Short half-life (~60-90 min) makes it titratable and reversible with protamine.",
                "comments": "Use UFH (not LMWH) when thrombolysis is being considered, when there is renal failure, or when procedural intervention may be needed (short half-life, reversible).",
            },
            {
                "name": "Systemic tPA — alteplase (massive PE)",
                "item_type": "medication",
                "dose": "100 mg IV over 2 hours (standard regimen). In cardiac arrest: 50 mg IV bolus, may repeat 50 mg if no ROSC.",
                "onset_peak_duration": "Clot lysis begins within minutes; peak fibrinolytic effect during and shortly after infusion.",
                "mechanism": "Converts plasminogen to plasmin, which lyses fibrin clot in pulmonary vasculature, reducing RV afterload.",
                "contra": "Active internal bleeding, recent (within 3 months) intracranial hemorrhage, intracranial neoplasm/AVM, recent intracranial or spinal surgery, active bleeding or bleeding diathesis, severe uncontrolled hypertension. In cardiac arrest from PE, relative contraindications are often overridden given otherwise fatal prognosis.",
                "comments": "Hold heparin during alteplase infusion, restart without bolus when aPTT <80. Have cryoprecipitate, TXA, and aminocaproic acid available for bleeding complications.",
            },
            {
                "name": "Cardiac arrest from PE",
                "item_type": "procedure",
                "summary": "Push-dose tPA during CPR. Prolonged resuscitation. Consider ECMO.",
                "steps": [
                    "Give alteplase 50 mg IV bolus during CPR. If no ROSC after 15 minutes, may repeat 50 mg (total 100 mg).",
                    "Continue CPR for at least 15-20 minutes after tPA administration (drug needs time + compressions to circulate and lyse clot).",
                    "Do not stop CPR early after lytic — these patients can have delayed ROSC.",
                    "If ECMO/ECPR is available and can be initiated rapidly, consider it (especially if pre-arrest submassive PE was identified).",
                    "If ROSC achieved, start heparin infusion (no bolus) when aPTT <80 and manage as post-ROSC + massive PE.",
                ],
                "cautions": "Fibrinolysis during CPR means bleeding risk is very high. This is a last-resort, life-saving intervention in a patient who will otherwise die.",
            },
            {
                "name": "Submassive PE — escalation considerations",
                "item_type": "procedure",
                "summary": "Anticoagulation is baseline. Escalate if deteriorating.",
                "steps": [
                    "Start heparin drip and admit to ICU or step-down for close hemodynamic monitoring.",
                    "Serial troponin and clinical reassessment every 4-6 hours for the first 24-48 hours.",
                    "Triggers for escalation: worsening tachycardia, new hypotension, rising lactate, increasing oxygen requirement, worsening RV function on echo.",
                    "Catheter-directed therapy (CDT): lower dose of tPA delivered directly to clot via IR catheter. Lower systemic bleeding risk than full-dose systemic lysis. Discuss with IR/interventional cardiology early if submassive with concerning features.",
                    "Systemic tPA: consider if patient deteriorates to massive physiology and CDT is not immediately available.",
                ],
                "cautions": "The line between submassive and massive PE is clinical deterioration. Have thrombolytics readily available and a low threshold to escalate.",
            },
        ],
    },
    "Naloxone": {
        "medications": [
            {
                "name": "Low-dose titration (breathing but oversedated)",
                "item_type": "medication",
                "dose": "0.04 mg (40 mcg) IV every 2-3 minutes, titrate to adequate respiratory rate and effort (goal RR ≥12, SpO2 >92%). Dilute: take 0.4 mg/1 mL vial, add 9 mL NS → 0.04 mg/mL, give 1 mL at a time.",
                "onset_peak_duration": "Onset 1-2 minutes IV; duration 30-90 minutes (shorter than most opioids).",
                "mechanism": "Competitive mu-opioid receptor antagonist. Displaces opioid from receptor.",
                "comments": "Goal is to restore adequate ventilation, NOT full alertness. Full reversal precipitates acute withdrawal: vomiting (aspiration risk), agitation, hypertension, tachycardia, pulmonary edema, and the patient will leave AMA. Titrate to breathing, not to talking.",
            },
            {
                "name": "Apneic / peri-arrest dosing",
                "item_type": "medication",
                "dose": "0.4 mg IV/IM/IO, repeat every 2-3 minutes. If no IV: 4 mg intranasal (standard Narcan nasal spray) or 0.4 mg IM. If no response after 10 mg total, reconsider the diagnosis (is this really an opioid overdose?).",
                "onset_peak_duration": "IV onset 1-2 minutes; IM onset 3-5 minutes; IN onset 3-5 minutes.",
                "comments": "Support ventilation with BVM while waiting for naloxone to work. Naloxone is not a substitute for airway management. If the patient is not breathing, bag them.",
            },
            {
                "name": "Naloxone infusion (long-acting opioid ingestion)",
                "item_type": "medication",
                "dose": "Infusion rate: 2/3 of the total bolus dose that achieved response, given per hour. Example: if 0.2 mg total was needed → infuse 0.13 mg/hr. Mix 2 mg in 500 mL NS (4 mcg/mL) and titrate. Reassess hourly.",
                "onset_peak_duration": "Continuous effect while infusing. Wean gradually and observe for recurrence.",
                "comments": "Indicated when re-sedation is expected: methadone, extended-release oxycodone/morphine, large ingestions, body packers. Naloxone half-life (30-90 min) is much shorter than these opioids. Without a drip, the patient will re-sedate.",
            },
            {
                "name": "Key reminders",
                "item_type": "procedure",
                "steps": [
                    "Naloxone wears off before most opioids. Always observe for re-sedation — minimum 4 hours after last naloxone dose for short-acting opioids, longer for methadone/extended-release.",
                    "If re-sedation occurs after bolus wears off, start a drip rather than chasing with repeated boluses.",
                    "Intranasal naloxone (4 mg) is the pre-hospital/bystander route. In the hospital, IV is preferred for titratability.",
                    "Consider the whole picture: opioid overdose patients are at risk for aspiration pneumonia, rhabdomyolysis (prolonged down time), compartment syndrome, and hypothermia.",
                    "If the patient wakes up and wants to leave: document capacity assessment and counsel on re-sedation risk. This is a high-risk AMA situation.",
                ],
            },
        ],
    },
}
